/* ============================================================
   DATOS — Porra Mundial 2026
   Expuesto en window.DB
   ============================================================ */
(function(){
  const FLAG = (code,w=80)=>`https://flagcdn.com/w${w}/${code}.png`;

  const T = {
    /* Grupo 1 — La Grasa Papa */
    arg:{name:'Argentina',  code:'ARG',f:'ar'},
    fra:{name:'Francia',    code:'FRA',f:'fr'},
    bra:{name:'Brasil',     code:'BRA',f:'br'},
    eng:{name:'Inglaterra', code:'ENG',f:'gb-eng'},
    esp:{name:'España',     code:'ESP',f:'es'},
    por:{name:'Portugal',   code:'POR',f:'pt'},
    /* Grupo 2 */
    ale:{name:'Alemania',   code:'ALE',f:'de'},
    nld:{name:'P. Bajos',   code:'NED',f:'nl'},
    bel:{name:'Bélgica',    code:'BEL',f:'be'},
    cro:{name:'Croacia',    code:'CRO',f:'hr'},
    /* Grupo 3 */
    usa:{name:'EE. UU.',    code:'USA',f:'us'},
    mex:{name:'México',     code:'MEX',f:'mx'},
    can:{name:'Canadá',     code:'CAN',f:'ca'},
    uru:{name:'Uruguay',    code:'URU',f:'uy'},
    col:{name:'Colombia',   code:'COL',f:'co'},
    /* Grupo 4 */
    jpn:{name:'Japón',      code:'JPN',f:'jp'},
    mar:{name:'Marruecos',  code:'MAR',f:'ma'},
    sen:{name:'Senegal',    code:'SEN',f:'sn'},
    ecu:{name:'Ecuador',    code:'ECU',f:'ec'},
    /* Grupo 5 — Relleno Mundialero */
    kor:{name:'Corea S.',   code:'KOR',f:'kr'},
    sui:{name:'Suiza',      code:'SUI',f:'ch'},
    den:{name:'Dinamarca',  code:'DEN',f:'dk'},
    aus:{name:'Australia',  code:'AUS',f:'au'},
    gha:{name:'Ghana',      code:'GHA',f:'gh'},
    pol:{name:'Polonia',    code:'POL',f:'pl'},
    /* Grupo 6 */
    tur:{name:'Turquía',    code:'TUR',f:'tr'},
    srb:{name:'Serbia',     code:'SRB',f:'rs'},
    ita:{name:'Italia',     code:'ITA',f:'it'},
    nig:{name:'Nigeria',    code:'NIG',f:'ng'},
    cam:{name:'Camerún',    code:'CAM',f:'cm'},
  };
  Object.keys(T).forEach(k=>{ T[k].id=k; T[k].flag=FLAG(T[k].f); T[k].flagHi=FLAG(T[k].f,160); });

  /* ---- Grupos de la PORRA (no los del Mundial) ---- */
  const porraGroups = [
    {id:1, name:'La Grasa Papa',      icon:'trophy', col:'#FDD301', pick:2, teams:['arg','fra','bra','eng','esp','por']},
    {id:2, name:'Los Europeos',       icon:'crown',  col:'#27E5D4', pick:2, teams:['ale','nld','bel','cro']},
    {id:3, name:'Las Américas',       icon:'globe',  col:'#ABCB2D', pick:2, teams:['usa','mex','can','uru','col']},
    {id:4, name:'Los Guerreros',      icon:'shield', col:'#F79516', pick:2, teams:['jpn','mar','sen','ecu']},
    {id:5, name:'Relleno Mundialero', icon:'dice',   col:'#8C6BFF', pick:1, teams:['kor','sui','den','aus','gha','pol'], multiplier:2.5},
    {id:6, name:'Los Valientes',      icon:'fire',   col:'#D8131A', pick:2, teams:['tur','srb','ita','nig','cam']},
  ];

  /* ---- Reglamento de puntuación ---- */
  const scoring = {
    price: 10,
    groupPhase: { win:3, draw:1, loss:0, first:5, second:3 },
    knockouts:  { r32:3, r16:5, qf:8, sf:10, final:15, champ:20 },
    goalscorer: { one:5, both:10 },
  };

  /* ---- Plantillas completas (29 selecciones) ---- */
  const P = (id,name,fullName,pos,club,num,g1)=>({id,name,fullName,pos,club,num,g1,goals:0,assists:0});

  const players = [
    /* ══════════════════════════════════════════
       GRUPO 1 — LA GRASA PAPA
    ══════════════════════════════════════════ */

    /* ── ARG ── */
    P('emiliano_martinez','E. Martínez','Emiliano Martínez','GK','Aston Villa',23,true),
    P('musso','J. Musso','Juan Musso','GK','Atlético Madrid',12,true),
    P('rulli_g','G. Rulli','Gerónimo Rulli','GK','Ajax',1,true),
    P('romero','C. Romero','Cristian Romero','DEF','Tottenham',13,true),
    P('lisandro','L. Martínez','Lisandro Martínez','DEF','Man. Utd',6,true),
    P('otamendi','Otamendi','Nicolás Otamendi','DEF','Benfica',19,true),
    P('molina','N. Molina','Nahuel Molina','DEF','Atlético Madrid',26,true),
    P('acuna','M. Acuña','Marcos Acuña','DEF','Sevilla',8,true),
    P('tagliafico','N. Tagliafico','Nicolás Tagliafico','DEF','Lyon',3,true),
    P('valentini_f','F. Valentini','Facundo Valentini','DEF','Boca Juniors',16,true),
    P('de_paul','R. De Paul','Rodrigo De Paul','MID','Atlético Madrid',7,true),
    P('mac_allister','A. Mac Allister','Alexis Mac Allister','MID','Liverpool',10,true),
    P('enzo','E. Fernández','Enzo Fernández','MID','Chelsea',24,true),
    P('palacios','E. Palacios','Exequiel Palacios','MID','Leverkusen',14,true),
    P('almada','T. Almada','Thiago Almada','MID','Lyon',17,true),
    P('messi','L. Messi','Lionel Messi','FWD','Inter Miami',10,true),
    P('lautaro','L. Martínez','Lautaro Martínez','FWD','Inter',22,true),
    P('julian','J. Álvarez','Julián Álvarez','FWD','Atlético Madrid',9,true),
    P('garnacho','A. Garnacho','Alejandro Garnacho','FWD','Man. Utd',11,true),
    P('dybala','P. Dybala','Paulo Dybala','FWD','Roma',21,true),

    /* ── FRA ── */
    P('maignan','M. Maignan','Mike Maignan','GK','AC Milan',16,true),
    P('samba','B. Samba','Brice Samba','GK','Lens',23,true),
    P('areola','A. Areola','Alphonse Areola','GK','West Ham',1,true),
    P('upamecano','D. Upamecano','Dayot Upamecano','DEF','Bayern',5,true),
    P('saliba','W. Saliba','William Saliba','DEF','Arsenal',12,true),
    P('konate_i','I. Konaté','Ibrahima Konaté','DEF','Liverpool',4,true),
    P('theo','T. Hernández','Theo Hernández','DEF','AC Milan',22,true),
    P('kounde','J. Koundé','Jules Koundé','DEF','Barcelona',2,true),
    P('camavinga','E. Camavinga','Eduardo Camavinga','MID','Real Madrid',14,true),
    P('tchouameni','A. Tchouaméni','Aurélien Tchouaméni','MID','Real Madrid',8,true),
    P('guendouzi','M. Guendouzi','Mattéo Guendouzi','MID','Lazio',6,true),
    P('griezmann','A. Griezmann','Antoine Griezmann','MID','Atlético Madrid',7,true),
    P('zaire_emery','W. Zaïre-Emery','Warren Zaïre-Emery','MID','PSG',17,true),
    P('mbappe','K. Mbappé','Kylian Mbappé','FWD','Real Madrid',9,true),
    P('dembele','O. Dembélé','Ousmane Dembélé','FWD','PSG',11,true),
    P('barcola','B. Barcola','Bradley Barcola','FWD','PSG',20,true),
    P('thuram_m','M. Thuram','Marcus Thuram','FWD','Inter',15,true),
    P('coman','K. Coman','Kingsley Coman','FWD','Bayern',18,true),

    /* ── BRA ── */
    P('alisson','Alisson','Alisson Becker','GK','Liverpool',1,true),
    P('ederson','Ederson','Ederson Moraes','GK','Man. City',12,true),
    P('bento_bra','Bento','Muriel Bento','GK','Al-Qadsiah',23,true),
    P('marquinhos','Marquinhos','Marquinhos','DEF','PSG',5,true),
    P('militao','É. Militão','Éder Militão','DEF','Real Madrid',3,true),
    P('gabriel_mag','G. Magalhães','Gabriel Magalhães','DEF','Arsenal',4,true),
    P('danilo_bra','Danilo','Danilo Luiz','DEF','Juventus',13,true),
    P('wendell','Wendell','Wendell','DEF','Porto',6,true),
    P('vanderson','Vanderson','Vanderson','DEF','Monaco',2,true),
    P('arana','G. Arana','Guilherme Arana','DEF','Atlético Mineiro',16,true),
    P('bruno_g','B. Guimarães','Bruno Guimarães','MID','Newcastle',8,true),
    P('paqueta','L. Paquetá','Lucas Paquetá','MID','West Ham',10,true),
    P('gerson','Gerson','Gerson Santos','MID','Flamengo',15,true),
    P('vinicius','Vinícius Jr.','Vinícius Júnior','FWD','Real Madrid',7,true),
    P('rodrygo','Rodrygo','Rodrygo Goes','FWD','Real Madrid',11,true),
    P('endrick','Endrick','Endrick Felipe','FWD','Real Madrid',16,true),
    P('raphinha','Raphinha','Raphinha Díaz','FWD','Barcelona',17,true),
    P('savinho','Savinho','Sávio Moreira','FWD','Man. City',26,true),
    P('esteao','Estêvão','Estêvão Willian','FWD','Chelsea',19,true),
    P('martinelli','G. Martinelli','Gabriel Martinelli','FWD','Arsenal',22,true),

    /* ── ENG ── */
    P('pickford','J. Pickford','Jordan Pickford','GK','Everton',1,true),
    P('raya','D. Raya','David Raya','GK','Arsenal',12,true),
    P('trafford','J. Trafford','James Trafford','GK','Burnley',23,true),
    P('walker','K. Walker','Kyle Walker','DEF','Man. City',2,true),
    P('trippier','K. Trippier','Kieran Trippier','DEF','Newcastle',22,true),
    P('stones','J. Stones','John Stones','DEF','Man. City',5,true),
    P('guehi','M. Guehi','Marc Guehi','DEF','Crystal Palace',6,true),
    P('konsa','E. Konsa','Ezri Konsa','DEF','Aston Villa',4,true),
    P('alexander_arnold','T. Alexander-Arnold','Trent Alexander-Arnold','MID','Real Madrid',66,true),
    P('bellingham','J. Bellingham','Jude Bellingham','MID','Real Madrid',10,true),
    P('rice','D. Rice','Declan Rice','MID','Arsenal',41,true),
    P('gallagher','C. Gallagher','Conor Gallagher','MID','Atlético Madrid',13,true),
    P('mainoo','K. Mainoo','Kobbie Mainoo','MID','Man. Utd',16,true),
    P('kane','H. Kane','Harry Kane','FWD','Bayern',9,true),
    P('saka','B. Saka','Bukayo Saka','FWD','Arsenal',7,true),
    P('rashford','M. Rashford','Marcus Rashford','FWD','Barcelona',11,true),
    P('foden','P. Foden','Phil Foden','FWD','Man. City',47,true),
    P('gordon','A. Gordon','Anthony Gordon','FWD','Newcastle',19,true),
    P('palmer','C. Palmer','Cole Palmer','FWD','Chelsea',20,true),

    /* ── ESP ── */
    P('simon_e','U. Simón','Unai Simón','GK','Athletic Club',1,true),
    P('raya_esp','D. Raya','David Raya','GK','Arsenal',23,true),
    P('remiro','A. Remiro','Álex Remiro','GK','Real Sociedad',13,true),
    P('le_normand','R. Le Normand','Robin Le Normand','DEF','Atlético Madrid',3,true),
    P('laporte_a','A. Laporte','Aymeric Laporte','DEF','Al-Nassr',14,true),
    P('garcia_eric','E. García','Eric García','DEF','Girona',24,true),
    P('cucurella','M. Cucurella','Marc Cucurella','DEF','Chelsea',18,true),
    P('grimaldo_e','Á. Grimaldo','Alejandro Grimaldo','DEF','Leverkusen',6,true),
    P('carvajal_d','D. Carvajal','Daniel Carvajal','DEF','Real Madrid',2,true),
    P('pedri','Pedri','Pedro González López','MID','Barcelona',8,true),
    P('rodri','Rodri','Rodri Hernández','MID','Man. City',16,true),
    P('gavi','Gavi','Pablo Gavi','MID','Barcelona',6,true),
    P('fabian_ruiz','F. Ruiz','Fabián Ruiz','MID','PSG',4,true),
    P('olmo','D. Olmo','Dani Olmo','MID','Barcelona',7,true),
    P('zubimendi','M. Zubimendi','Martín Zubimendi','MID','Arsenal',20,true),
    P('yamal','L. Yamal','Lamine Yamal','FWD','Barcelona',19,true),
    P('torres_f','F. Torres','Ferran Torres','FWD','Barcelona',11,true),
    P('williams_n','N. Williams','Nico Williams','FWD','Athletic Club',17,true),
    P('morata','Á. Morata','Álvaro Morata','FWD','AC Milan',9,true),
    P('oyarzabal','M. Oyarzabal','Mikel Oyarzabal','FWD','Real Sociedad',21,true),

    /* ── POR ── */
    P('diogo_costa','D. Costa','Diogo Costa','GK','Porto',1,true),
    P('patricio','R. Patrício','Rui Patrício','GK','Roma',12,true),
    P('sa_j','J. Sá','José Sá','GK','Wolverhampton',23,true),
    P('cancelo','J. Cancelo','João Cancelo','DEF','Barcelona',20,true),
    P('dias_r','R. Dias','Rúben Dias','DEF','Man. City',4,true),
    P('inacio_g','G. Inácio','Gonçalo Inácio','DEF','Sporting CP',3,true),
    P('nuno_mendes','N. Mendes','Nuno Mendes','DEF','PSG',25,true),
    P('semedo','N. Semedo','Nélson Semedo','DEF','Wolverhampton',2,true),
    P('fernandes_b','B. Fernandes','Bruno Fernandes','MID','Man. Utd',8,true),
    P('vitinha','Vitinha','Vítor Machado Ferreira','MID','PSG',11,true),
    P('neves_r','R. Neves','Rúben Neves','MID','Al-Hilal',15,true),
    P('bernardo','B. Silva','Bernardo Silva','MID','Man. City',10,true),
    P('palhinha','J. Palhinha','João Palhinha','MID','Bayern',26,true),
    P('ronaldo','C. Ronaldo','Cristiano Ronaldo','FWD','Al-Nassr',7,true),
    P('leao','R. Leão','Rafael Leão','FWD','AC Milan',17,true),
    P('jota','D. Jota','Diogo Jota','FWD','Liverpool',20,true),
    P('felix_j','J. Félix','João Félix','FWD','Chelsea',9,true),
    P('horta','R. Horta','Ricardo Horta','FWD','Braga',21,true),
    P('gramos','G. Ramos','Gonçalo Ramos','FWD','PSG',18,true),

    /* ══════════════════════════════════════════
       GRUPO 2 — LOS EUROPEOS
    ══════════════════════════════════════════ */

    /* ── ALE ── */
    P('ter_stegen','M. ter Stegen','Marc-André ter Stegen','GK','Barcelona',1,false),
    P('baumann_o','O. Baumann','Oliver Baumann','GK','Hoffenheim',12,false),
    P('nubel','A. Nübel','Alexander Nübel','GK','Stuttgart',23,false),
    P('rudiger','A. Rüdiger','Antonio Rüdiger','DEF','Real Madrid',2,false),
    P('schlotterbeck','N. Schlotterbeck','Nico Schlotterbeck','DEF','BVB',15,false),
    P('tah_j','J. Tah','Jonathan Tah','DEF','Bayern',4,false),
    P('raum','D. Raum','David Raum','DEF','Leipzig',5,false),
    P('mittelstadt','M. Mittelstädt','Maximilian Mittelstädt','DEF','Stuttgart',14,false),
    P('kimmich','J. Kimmich','Joshua Kimmich','MID','Bayern',6,false),
    P('goretzka','L. Goretzka','Leon Goretzka','MID','Bayern',8,false),
    P('andrich','R. Andrich','Robert Andrich','MID','Leverkusen',17,false),
    P('fuhrich_c','C. Führich','Chris Führich','MID','Stuttgart',21,false),
    P('musiala','J. Musiala','Jamal Musiala','FWD','Bayern',10,false),
    P('wirtz','F. Wirtz','Florian Wirtz','FWD','Bayern',11,false),
    P('havertz_k','K. Havertz','Kai Havertz','FWD','Arsenal',7,false),
    P('gnabry','S. Gnabry','Serge Gnabry','FWD','Bayern',14,false),
    P('fullkrug','N. Füllkrug','Niclas Füllkrug','FWD','West Ham',9,false),
    P('sane','L. Sané','Leroy Sané','FWD','Bayern',19,false),

    /* ── NLD ── */
    P('flekken_b','M. Flekken','Mark Flekken','GK','Arsenal',1,false),
    P('bijlow','J. Bijlow','Justin Bijlow','GK','Feyenoord',22,false),
    P('drommel','M. Drommel','Maarten Drommel','GK','PSV',23,false),
    P('van_dijk','V. van Dijk','Virgil van Dijk','DEF','Liverpool',4,false),
    P('de_ligt_m','M. de Ligt','Matthijs de Ligt','DEF','Man. Utd',3,false),
    P('timber','J. Timber','Jurriën Timber','DEF','Arsenal',21,false),
    P('dumfries','D. Dumfries','Denzel Dumfries','DEF','Inter',2,false),
    P('maatsen','I. Maatsen','Ian Maatsen','DEF','Chelsea',17,false),
    P('ake','N. Aké','Nathan Aké','DEF','Man. City',5,false),
    P('de_jong_f','F. de Jong','Frenkie de Jong','MID','Barcelona',8,false),
    P('simons','X. Simons','Xavi Simons','MID','Leipzig',22,false),
    P('gravenberch','R. Gravenberch','Ryan Gravenberch','MID','Liverpool',16,false),
    P('veerman','J. Veerman','Joey Veerman','MID','PSV',14,false),
    P('gakpo','C. Gakpo','Cody Gakpo','FWD','Liverpool',11,false),
    P('depay','M. Depay','Memphis Depay','FWD','Atlético Madrid',10,false),
    P('zirkzee','J. Zirkzee','Joshua Zirkzee','FWD','Man. Utd',9,false),
    P('malen','D. Malén','Donyell Malén','FWD','BVB',7,false),

    /* ── BEL ── */
    P('casteels_k','K. Casteels','Koen Casteels','GK','Al-Qadsiah',1,false),
    P('sels','M. Sels','Matz Sels','GK','Nottingham F.',23,false),
    P('kaminski','T. Kaminski','Thomas Kaminski','GK','Luton',12,false),
    P('faes','W. Faes','Wout Faes','DEF','Leicester',3,false),
    P('theate','A. Theate','Arthur Theate','DEF','Rennes',4,false),
    P('castagne','T. Castagne','Timothy Castagne','DEF','Fulham',22,false),
    P('de_cuyper','M. De Cuyper','Maxim De Cuyper','DEF','Club Brugge',6,false),
    P('debast','Z. Debast','Zeno Debast','DEF','Anderlecht',2,false),
    P('de_bruyne','K. De Bruyne','Kevin De Bruyne','MID','Man. City',7,false),
    P('tielemans','Y. Tielemans','Youri Tielemans','MID','Aston Villa',8,false),
    P('vanaken_h','H. Vanaken','Hans Vanaken','MID','Club Brugge',6,false),
    P('saelemaekers','A. Saelemaekers','Alexis Saelemaekers','MID','Roma',11,false),
    P('carrasco_y','Y. Carrasco','Yannick Carrasco','MID','Al-Shabab',10,false),
    P('lukaku_r','R. Lukaku','Romelu Lukaku','FWD','Napoli',9,false),
    P('doku','J. Doku','Jérémy Doku','FWD','Man. City',11,false),
    P('trossard_l','L. Trossard','Leandro Trossard','FWD','Arsenal',17,false),
    P('openda_l','L. Openda','Lois Openda','FWD','Leipzig',19,false),

    /* ── CRO ── */
    P('livakovic','D. Livaković','Dominik Livaković','GK','Fenerbahçe',1,false),
    P('ivusic','I. Ivušić','Ivan Ivušić','GK','Osijek',12,false),
    P('rados_i','I. Radoš','Ivan Radoš','GK','Hajduk Split',23,false),
    P('gvardiol','J. Gvardiol','Joško Gvardiol','DEF','Man. City',6,false),
    P('sutalo','I. Šutalo','Igor Šutalo','DEF','Ajax',5,false),
    P('sosa_b','B. Sosa','Borna Sosa','DEF','Ajax',3,false),
    P('juranovic','J. Juranović','Josip Juranović','DEF','Celtic',2,false),
    P('erlic','M. Erlić','Martin Erlić','DEF','Leipzig',4,false),
    P('modric','L. Modrić','Luka Modrić','MID','Real Madrid',10,false),
    P('kovacic','M. Kovačić','Mateo Kovačić','MID','Man. City',8,false),
    P('sucic_l','L. Sučić','Luka Sučić','MID','Salzburg',16,false),
    P('majer','L. Majer','Lovro Majer','MID','Rennes',18,false),
    P('pasalic','M. Pašalić','Mario Pašalić','MID','Atalanta',19,false),
    P('kramaric','A. Kramarić','Andrej Kramarić','FWD','Hoffenheim',9,false),
    P('budimir','A. Budimir','Ante Budimir','FWD','Osasuna',7,false),
    P('livaja_m','M. Livaja','Marko Livaja','FWD','Hajduk Split',17,false),

    /* ══════════════════════════════════════════
       GRUPO 3 — LAS AMÉRICAS
    ══════════════════════════════════════════ */

    /* ── USA ── */
    P('turner_m','M. Turner','Matt Turner','GK','Nottingham F.',1,false),
    P('horvath','E. Horváth','Ethan Horváth','GK','Luton',12,false),
    P('schulte_p','P. Schulte','Patrick Schulte','GK','Columbus',23,false),
    P('dest','S. Dest','Sergino Dest','DEF','PSV',2,false),
    P('scally','J. Scally','Joe Scally','DEF','Gladbach',4,false),
    P('long_a','A. Long','Aaron Long','DEF','Vancouver',5,false),
    P('robinson_a','A. Robinson','Antonee Robinson','DEF','Fulham',3,false),
    P('carter_vickers','C. Carter-Vickers','Cameron Carter-Vickers','DEF','Celtic',15,false),
    P('musah','Y. Musah','Yunus Musah','MID','AC Milan',8,false),
    P('adams_t','T. Adams','Tyler Adams','MID','Bournemouth',4,false),
    P('mckennie','W. McKennie','Weston McKennie','MID','Juventus',5,false),
    P('reyna','G. Reyna','Giovanni Reyna','MID','BVB',7,false),
    P('acosta','K. Acosta','Kellyn Acosta','MID','LA Galaxy',16,false),
    P('tillman','M. Tillman','Malik Tillman','MID','PSV',17,false),
    P('pulisic','C. Pulisic','Christian Pulisic','FWD','AC Milan',10,false),
    P('weah_t','T. Weah','Tim Weah','FWD','Juventus',11,false),
    P('balogun','F. Balogun','Folarin Balogun','FWD','Monaco',9,false),
    P('ferreira_j','J. Ferreira','Jesús Ferreira','FWD','Dallas',19,false),
    P('pepi','R. Pepi','Ricardo Pepi','FWD','PSV',22,false),

    /* ── MEX ── */
    P('ochoa','G. Ochoa','Guillermo Ochoa','GK','Salernitana',13,false),
    P('gonzalez_j','J. González','Julio González','GK','Cruz Azul',1,false),
    P('cota','R. Cota','Rodolfo Cota','GK','León',23,false),
    P('montes_c','C. Montes','César Montes','DEF','Espanyol',3,false),
    P('vasquez_j','J. Vásquez','Johan Vásquez','DEF','Genoa',5,false),
    P('arteaga','G. Arteaga','Gerardo Arteaga','DEF','Genk',6,false),
    P('sanchez_j','J. Sánchez','Jorge Sánchez','DEF','Atlas',2,false),
    P('gallardo_jes','J. Gallardo','Jesús Gallardo','DEF','Monterrey',15,false),
    P('edson_alvarez','E. Álvarez','Edson Álvarez','MID','West Ham',14,false),
    P('herrera_e','H. Herrera','Héctor Herrera','MID','Houston',16,false),
    P('lainez','D. Laínez','Diego Laínez','MID','Betis',22,false),
    P('antuna','U. Antuna','Uriel Antuna','MID','Cruz Azul',21,false),
    P('vega_c','C. Vega','Carlos Vega','MID','Tigres',11,false),
    P('jimenez_r','R. Jiménez','Raúl Jiménez','FWD','Fulham',9,false),
    P('lozano','H. Lozano','Hirving Lozano','FWD','PSV',7,false),
    P('martin_h','H. Martín','Henry Martín','FWD','América',10,false),
    P('gimenez_s','S. Giménez','Santiago Giménez','FWD','AC Milan',18,false),

    /* ── CAN ── */
    P('borjan','M. Borjan','Milan Borjan','GK','Red Star',1,false),
    P('crepeau','M. Crépeau','Maxime Crépeau','GK','LA Galaxy',12,false),
    P('laborde_c','C. Laborde','Colin Laborde','GK','CF Montréal',23,false),
    P('davies_a','A. Davies','Alphonso Davies','DEF','Bayern',3,false),
    P('johnston','A. Johnston','Alistair Johnston','DEF','Celtic',2,false),
    P('cornelius_d','D. Cornelius','Derek Cornelius','DEF','Malmö',5,false),
    P('miller_k','K. Miller','Kamal Miller','DEF','MLS',4,false),
    P('laryea','R. Laryea','Richie Laryea','DEF','Toronto',22,false),
    P('eustaquio','S. Eustaquio','Stephen Eustáquio','MID','Porto',7,false),
    P('osorio','J. Osorio','Jonathan Osorio','MID','Toronto',20,false),
    P('kone_i','I. Koné','Ismaël Koné','MID','Watford',16,false),
    P('millar_l','L. Millar','Liam Millar','MID','Basel',11,false),
    P('buchanan','T. Buchanan','Tajon Buchanan','MID','Bruges',14,false),
    P('david_j','J. David','Jonathan David','FWD','Lille',9,false),
    P('larin_c','C. Larin','Cyle Larin','FWD','Mallorca',18,false),
    P('diallo_can','A. Diallo','Aliou Diallo','FWD','CF Montréal',21,false),

    /* ── URU ── */
    P('rochet','S. Rochet','Sergio Rochet','GK','Nacional',1,false),
    P('de_amores','G. de Amores','Guillermo de Amores','GK','Peñarol',12,false),
    P('laborda_m','M. Laborda','Mathías Laborda','GK','Defensor',23,false),
    P('araujo_r','R. Araújo','Ronald Araújo','DEF','Barcelona',4,false),
    P('gimenez_j','J.M. Giménez','José María Giménez','DEF','Atlético Madrid',3,false),
    P('olivera','M. Olivera','Mathías Olivera','DEF','Napoli',22,false),
    P('vina','M. Viña','Mathías Viña','DEF','Roma',19,false),
    P('nandez','N. Nández','Nahitan Nández','DEF','Cagliari',25,false),
    P('bentancur','R. Bentancur','Rodrigo Bentancur','MID','Tottenham',5,false),
    P('valverde','F. Valverde','Fede Valverde','MID','Real Madrid',8,false),
    P('ugarte','M. Ugarte','Manuel Ugarte','MID','Man. Utd',16,false),
    P('de_la_cruz','N. De la Cruz','Nicolás De la Cruz','MID','Flamengo',10,false),
    P('nunez_d','D. Núñez','Darwin Núñez','FWD','Liverpool',11,false),
    P('pellistri','F. Pellistri','Facundo Pellistri','FWD','Man. Utd',7,false),
    P('maxi_gomez','M. Gómez','Maxi Gómez','FWD','Espanyol',9,false),
    P('rodriguez_c_uru','C. Rodríguez','Carlos Rodríguez','FWD','Flamengo',17,false),

    /* ── COL ── */
    P('vargas_c','C. Vargas','Camilo Vargas','GK','Deportivo Cali',1,false),
    P('montero_a','Á. Montero','Álvaro Montero','GK','Millonarios',12,false),
    P('mora_col','A. Mora','Aldair Moreno','GK','Peñarol',23,false),
    P('munoz_d','D. Muñoz','Daniel Muñoz','DEF','Crystal Palace',2,false),
    P('davinson','D. Sánchez','Davinson Sánchez','DEF','Galatasaray',4,false),
    P('cuesta_c','C. Cuesta','Carlos Cuesta','DEF','Genk',5,false),
    P('mojica','J. Mojica','Johan Mojica','DEF','Girona',3,false),
    P('arias_j','J. Arias','Jhon Arias','MID','Fluminense',11,false),
    P('james','J. Rodríguez','James Rodríguez','MID','Rayo Vallecano',10,false),
    P('lerma','J. Lerma','Jefferson Lerma','MID','Crystal Palace',8,false),
    P('rios_r','R. Ríos','Richard Ríos','MID','Palmeiras',16,false),
    P('quintero_jf','J.F. Quintero','Juan Fernando Quintero','MID','Racing Club',7,false),
    P('diaz_l','L. Díaz','Luis Díaz','FWD','Liverpool',23,false),
    P('sinisterra','L. Sinisterra','Luis Sinisterra','FWD','Bournemouth',22,false),
    P('borre_r','R. Borré','Rafael Borré','FWD','Eintracht',9,false),
    P('duran_j','J. Durán','Jhon Durán','FWD','Aston Villa',19,false),

    /* ══════════════════════════════════════════
       GRUPO 4 — LOS GUERREROS
    ══════════════════════════════════════════ */

    /* ── JPN ── */
    P('suzuki_z','Z. Suzuki','Zion Suzuki','GK','Sint-Truiden',1,false),
    P('schmidt_d','D. Schmidt','Daniel Schmidt','GK','Sint-Truiden',12,false),
    P('nakamura_ko','K. Nakamura','Kosuke Nakamura','GK','Urawa Reds',23,false),
    P('tomiyasu','T. Tomiyasu','Takehiro Tomiyasu','DEF','Arsenal',5,false),
    P('itakura','K. Itakura','Kö Itakura','DEF','Gladbach',3,false),
    P('taniguchi_h','H. Taniguchi','Hiroki Taniguchi','DEF','Kawasaki',4,false),
    P('sugawara_y','Y. Sugawara','Yukinari Sugawara','DEF','AZ',2,false),
    P('hirose_t','T. Hirose','Taichi Hirose','DEF','Gent',15,false),
    P('endo_w','W. Endo','Wataru Endo','MID','Liverpool',6,false),
    P('kamada','D. Kamada','Daichi Kamada','MID','Crystal Palace',14,false),
    P('tanaka_a','A. Tanaka','Ao Tanaka','MID','Düsseldorf',17,false),
    P('shibasaki','G. Shibasaki','Gaku Shibasaki','MID','UD Las Palmas',20,false),
    P('kubo_t','T. Kubo','Takefusa Kubo','FWD','Real Sociedad',10,false),
    P('mitoma','K. Mitoma','Kaoru Mitoma','FWD','Brighton',11,false),
    P('maeda_d','D. Maeda','Daizen Maeda','FWD','Celtic',9,false),
    P('asano','T. Asano','Takuma Asano','FWD','Bochum',13,false),
    P('ueda_a','A. Ueda','Ayase Ueda','FWD','Feyenoord',22,false),
    P('minamino','T. Minamino','Takumi Minamino','FWD','Monaco',18,false),

    /* ── MAR ── */
    P('bounou','Y. Bounou','Yassine Bounou','GK','Al-Hilal',1,false),
    P('tagnaouti','A. Tagnaouti','Ahmed Reda Tagnaouti','GK','Wydad',12,false),
    P('maimoun_c','C. Maimoun','Anas Zniti','GK','FAR Rabat',23,false),
    P('hakimi','A. Hakimi','Achraf Hakimi','DEF','PSG',2,false),
    P('mazraoui','N. Mazraoui','Noussair Mazraoui','DEF','Man. Utd',22,false),
    P('aguerd','N. Aguerd','Nayef Aguerd','DEF','West Ham',4,false),
    P('saiss_r','R. Saïss','Romain Saïss','DEF','Beşiktaş',5,false),
    P('attiat_allah','A. Attiat-Allah','Adam Attiat-Allah','DEF','Wydad',3,false),
    P('amrabat_s','S. Amrabat','Sofyan Amrabat','MID','Man. Utd',6,false),
    P('ounahi','A. Ounahi','Azzedine Ounahi','MID','Marseille',8,false),
    P('sabiri','A. Sabiri','Abdelhamid Sabiri','MID','Fiorentina',14,false),
    P('brahim','B. Díaz','Brahim Díaz','MID','Real Madrid',10,false),
    P('en_nesyri','Y. En-Nesyri','Youssef En-Nesyri','FWD','Fenerbahçe',9,false),
    P('ziyech','H. Ziyech','Hakim Ziyech','FWD','Galatasaray',7,false),
    P('boufal','S. Boufal','Sofiane Boufal','FWD','Angers',11,false),
    P('abde','A. Abde','Abde Ezzalzouli','FWD','Osasuna',19,false),

    /* ── SEN ── */
    P('gomis','A. Gomis','Alfred Gomis','GK','Rennes',1,false),
    P('dieng_s','S. Dieng','Seny Dieng','GK','QPR',12,false),
    P('diaw_m','M. Diaw','Mory Diaw','GK','Al-Kholood',23,false),
    P('koulibaly','K. Koulibaly','Kalidou Koulibaly','DEF','Al-Hilal',3,false),
    P('niakhate','M. Niakhaté','Moussa Niakhaté','DEF','Nottingham F.',5,false),
    P('cisse_pa','P.A. Cissé','Pape Abou Cissé','DEF','Olympiakos',4,false),
    P('ballo_toure','F. Ballo-Touré','Fodé Ballo-Touré','DEF','AC Milan',22,false),
    P('diallo_a','A. Diallo','Abdou Diallo','DEF','Leipzig',6,false),
    P('ganegueye','I.G. Gueye','Idrissa Gana Gueye','MID','Everton',8,false),
    P('papegueye','P. Gueye','Pape Gueye','MID','Villarreal',14,false),
    P('laminecamara','L. Camara','Lamine Camara','MID','Monaco',7,false),
    P('habibdiarra','H. Diarra','Habib Diarra','MID','Sunderland',19,false),
    P('pathe_ciss','P. Ciss','Pathé Ciss','MID','Rayo Vallecano',10,false),
    P('pmatsarr','P.M. Sarr','Pape Matar Sarr','MID','Tottenham',20,false),
    P('mane','S. Mané','Sadio Mané','FWD','Al-Nassr',10,false),
    P('isarr','I. Sarr','Ismaïla Sarr','FWD','Crystal Palace',11,false),
    P('ilimanndiaye','I. Ndiaye','Iliman Ndiaye','FWD','Everton',17,false),
    P('nicjackson','N. Jackson','Nicolas Jackson','FWD','Chelsea',9,false),
    P('assanediao','A. Diao','Assane Diao','FWD','Como',25,false),

    /* ── ECU ── */
    P('adominguez','A. Domínguez','Alexander Domínguez','GK','Liga de Quito',1,false),
    P('hgalindez','H. Galíndez','Hernán Galíndez','GK','Aucas',12,false),
    P('mramirez','M. Ramírez','Moisés Ramírez','GK','Barcelona SC',23,false),
    P('wpach','W. Pacho','Willian Pacho','DEF','PSG',4,false),
    P('phincapie','P. Hincapié','Piero Hincapié','DEF','Arsenal',3,false),
    P('pestupinian','P. Estupiñán','Pervis Estupiñán','DEF','AC Milan',16,false),
    P('ftorres','F. Torres','Félix Torres','DEF','Santos Laguna',5,false),
    P('apreciado','Á. Preciado','Ángelo Preciado','DEF','Genk',22,false),
    P('jporozo','J. Porozo','Jackson Porozo','DEF','Troyes',6,false),
    P('jor_ordonez','J. Ordóñez','Joel Ordóñez','DEF','Leverkusen',2,false),
    P('mcaicedo','M. Caicedo','Moisés Caicedo','MID','Chelsea',10,false),
    P('kendry_paez','K. Páez','Kendry Páez','MID','Chelsea',20,false),
    P('jeremy_sarmiento','J. Sarmiento','Jeremy Sarmiento','MID','Brighton',11,false),
    P('afranco','A. Franco','Alan Franco','MID','Talleres',8,false),
    P('jhmendez','J. Méndez','Jhegson Méndez','MID','LA Galaxy',5,false),
    P('pvite','P. Vite','Pedro Vite','MID','Vancouver',18,false),
    P('e_valencia','E. Valencia','Enner Valencia','FWD','Pachuca',13,false),
    P('gplata','G. Plata','Gonzalo Plata','FWD','Al-Qadsiah',7,false),
    P('krodriguez','K. Rodríguez','Kevin Rodríguez','FWD','Ipswich',9,false),
    P('lcampana','L. Campana','Leonardo Campana','FWD','Inter Miami',25,false),

    /* ══════════════════════════════════════════
       GRUPO 5 — RELLENO MUNDIALERO
    ══════════════════════════════════════════ */

    /* ── KOR ── */
    P('kim_seung_gyu','S.G. Kim','Kim Seung-gyu','GK','Vissel Kobe',1,false),
    P('jo_hyeon_woo','H.W. Jo','Jo Hyeon-woo','GK','Ulsan',12,false),
    P('ahn_jun_su','J.S. Ahn','Ahn Jun-su','GK','Jeonbuk',23,false),
    P('kim_min_jae','M.J. Kim','Kim Min-jae','DEF','Bayern',3,false),
    P('kim_jin_su','J.S. Kim','Kim Jin-su','DEF','Jeonbuk',4,false),
    P('lee_yong','Yong Lee','Lee Yong','DEF','Jeonbuk',2,false),
    P('kim_tae_hwan','T.H. Kim','Kim Tae-hwan','DEF','Ulsan',5,false),
    P('hong_chul','H.C. Hong','Hong Chul','DEF','Ulsan',6,false),
    P('lee_kang_in','K.I. Lee','Lee Kang-in','MID','PSG',10,false),
    P('hwang_in_beom','I.B. Hwang','Hwang In-beom','MID','Feyenoord',6,false),
    P('paik','S.H. Paik','Paik Seung-ho','MID','Jeonbuk',8,false),
    P('bae_jun_ho','J.H. Bae','Bae Jun-ho','MID','Stoke',17,false),
    P('na_sang_ho','S.H. Na','Na Sang-ho','MID','Crystal Palace',14,false),
    P('son_hm','H.M. Son','Son Heung-min','FWD','Tottenham',7,false),
    P('hwang_hee_chan','H.C. Hwang','Hwang Hee-chan','FWD','Wolves',9,false),
    P('cho_gue_sung','G.S. Cho','Cho Gue-sung','FWD','Freiburg',19,false),
    P('oh_se_hun','S.H. Oh','Oh Se-hun','FWD','Ulsan',18,false),

    /* ── SUI ── */
    P('kobel','G. Kobel','Gregor Kobel','GK','BVB',1,false),
    P('mvogo_sui','Y. Mvogo','Yvon Mvogo','GK','Lorient',12,false),
    P('mkeller','M. Keller','Marvin Keller','GK','Young Boys',23,false),
    P('akanji','M. Akanji','Manuel Akanji','DEF','Man. City',5,false),
    P('elvedi','N. Elvedi','Nico Elvedi','DEF','Gladbach',3,false),
    P('rrodriguez','R. Rodríguez','Ricardo Rodríguez','DEF','Real Betis',13,false),
    P('widmer','S. Widmer','Silvan Widmer','DEF','Mainz',2,false),
    P('comert','E. Comert','Eray Comert','DEF','Valencia',4,false),
    P('amenda','A. Amenda','Aurèle Amenda','DEF','Frankfurt',6,false),
    P('xhaka','G. Xhaka','Granit Xhaka','MID','Sunderland',10,false),
    P('freuler','R. Freuler','Remo Freuler','MID','Bologna',8,false),
    P('jashari','A. Jashari','Ardon Jashari','MID','AC Milan',6,false),
    P('sow','D. Sow','Djibril Sow','MID','Sevilla',15,false),
    P('aebischer','M. Aebischer','Michel Aebischer','MID','Pisa',17,false),
    P('rvargas','R. Vargas','Ruben Vargas','MID','Sevilla',11,false),
    P('zakaria','D. Zakaria','Denis Zakaria','MID','Monaco',20,false),
    P('embolo','B. Embolo','Breel Embolo','FWD','Rennes',7,false),
    P('amdouni','Z. Amdouni','Zeki Amdouni','FWD','Burnley',9,false),
    P('ndoye','D. Ndoye','Dan Ndoye','FWD','Nottingham F.',18,false),
    P('okafor','N. Okafor','Noah Okafor','FWD','Leeds',22,false),

    /* ── DEN ── */
    P('schmeichel_k','K. Schmeichel','Kasper Schmeichel','GK','Anderlecht',1,false),
    P('hermansen','M. Hermansen','Mads Hermansen','GK','Leicester',12,false),
    P('ronnow','F. Rønnow','Frederik Rønnow','GK','Union Berlin',23,false),
    P('andersen_j','J. Andersen','Joachim Andersen','DEF','Crystal Palace',4,false),
    P('vestergaard','J. Vestergaard','Jannik Vestergaard','DEF','Leicester',5,false),
    P('kristensen','R. Kristensen','Rasmus Kristensen','DEF','Frankfurt',2,false),
    P('maehle','J. Mæhle','Joakim Mæhle','DEF','Wolfsburg',3,false),
    P('bah','A. Bah','Alexander Bah','DEF','Benfica',16,false),
    P('nelsson','V. Nelsson','Victor Nelsson','DEF','Galatasaray',6,false),
    P('eriksen','C. Eriksen','Christian Eriksen','MID','Wolfsburg',10,false),
    P('hojbjerg','P.E. Højbjerg','Pierre-Emile Højbjerg','MID','Marseille',8,false),
    P('norgaard','C. Nørgaard','Christian Nørgaard','MID','Arsenal',6,false),
    P('damsgaard','M. Damsgaard','Mikkel Damsgaard','MID','Brentford',7,false),
    P('isaksen','G. Isaksen','Gustav Isaksen','MID','Lazio',11,false),
    P('skov_olsen','A. Skov Olsen','Andreas Skov Olsen','MID','Club Brugge',19,false),
    P('hojlund','R. Højlund','Rasmus Højlund','FWD','Napoli',9,false),
    P('dolberg','K. Dolberg','Kasper Dolberg','FWD','Anderlecht',21,false),
    P('wind','J. Wind','Jonas Wind','FWD','Wolfsburg',24,false),
    P('bruun_larsen','J. Bruun Larsen','Jakob Bruun Larsen','FWD','Stuttgart',22,false),

    /* ── AUS ── */
    P('matryan','M. Ryan','Mat Ryan','GK','Real Sociedad',1,false),
    P('izzo','P. Izzo','Paul Izzo','GK','Hellas Verona',12,false),
    P('gauci','J. Gauci','Joe Gauci','GK','Aston Villa',23,false),
    P('souttar','H. Souttar','Harry Souttar','DEF','Leicester',3,false),
    P('burgess','C. Burgess','Cameron Burgess','DEF','Swansea',4,false),
    P('circati','A. Circati','Alessandro Circati','DEF','Parma',5,false),
    P('behich','A. Behich','Aziz Behich','DEF','Dundee Utd',14,false),
    P('rowles','K. Rowles','Kye Rowles','DEF','Hearts',6,false),
    P('degenek','M. Degenek','Milos Degenek','DEF','Columbus',2,false),
    P('airvine','J. Irvine','Jackson Irvine','MID','FC St. Pauli',8,false),
    P('hrustic','A. Hrustic','Ajdin Hrustic','MID','Hellas Verona',10,false),
    P('mcgree','R. McGree','Riley McGree','MID','Middlesbrough',7,false),
    P('irankunda','N. Irankunda','Nestory Irankunda','MID','Bayern',20,false),
    P('mabil','A. Mabil','Awer Mabil','MID','Panathinaikos',19,false),
    P('leckie','M. Leckie','Mathew Leckie','MID','Melbourne City',11,false),
    P('mboyle','M. Boyle','Martin Boyle','FWD','Al-Faisaly',9,false),
    P('yengi','T. Yengi','Tete Yengi','FWD','Adelaide Utd',21,false),
    P('borrello','B. Borrello','Brandon Borrello','FWD','Freiburg',25,false),

    /* ── GHA ── */
    P('atizigi','L. Ati-Zigi','Lawrence Ati-Zigi','GK','St. Gallen',1,false),
    P('anang','J. Anang','Joseph Anang','GK','St Patrick\'s',12,false),
    P('aasare','B. Asare','Benjamín Asare','GK','Hearts of Oak',23,false),
    P('djiku','A. Djiku','Alexander Djiku','DEF','Spartak Moscow',5,false),
    P('aseidu','A. Seidu','Alidu Seidu','DEF','Rennes',2,false),
    P('amumin','A. Mumin','Abdul Mumin','DEF','Rayo Vallecano',4,false),
    P('bararahman','B.A. Rahman','Baba Abdul Rahman','DEF','PAOK',3,false),
    P('gidmensh','G. Mensah','Gideon Mensah','DEF','Auxerre',13,false),
    P('jopoku','J. Opoku','Jerome Opoku','DEF','Başakşehir',6,false),
    P('tpartey','T. Partey','Thomas Partey','MID','Villarreal',5,false),
    P('aissahaku','A.F. Issahaku','Abdul Fatawu Issahaku','MID','Leicester',10,false),
    P('ksulemana','K. Sulemana','Kamal Deen Sulemana','MID','Atalanta',11,false),
    P('aboakye','A. Boakye','Augustine Boakye','MID','Saint-Étienne',14,false),
    P('inkwilliams','I. Williams','Iñaki Williams','FWD','Athletic Club',9,false),
    P('jayew','J. Ayew','Jordan Ayew','FWD','Leicester',7,false),
    P('enumah','E. Nuamah','Ernest Nuamah','FWD','Lyon',11,false),
    P('asemenyo','A. Semenyo','Antoine Semenyo','FWD','Man. City',17,false),
    P('cbbaah','C. Bonsu Baah','Christopher Bonsu Baah','FWD','Al-Qadisiyah',18,false),

    /* ══════════════════════════════════════════
       GRUPO 6 — LOS VALIENTES
    ══════════════════════════════════════════ */

    /* ── TUR ── */
    P('mgunok','M. Günok','Mert Günok','GK','Fenerbahçe',1,false),
    P('altaybayindir','A. Bayındır','Altay Bayındır','GK','Man. Utd',23,false),
    P('ugcakir','U. Çakır','Uğurcan Çakır','GK','Galatasaray',12,false),
    P('merihdemiral','M. Demiral','Merih Demiral','DEF','Al-Ahli',3,false),
    P('obardakci','A. Bardakcı','Abdülkerim Bardakcı','DEF','Galatasaray',4,false),
    P('ozankabak','O. Kabak','Ozan Kabak','DEF','Hoffenheim',5,false),
    P('fkadıoglu','F. Kadıoğlu','Ferdi Kadıoğlu','DEF','Brighton',22,false),
    P('mcelık','Z. Çelik','Zeki Çelik','DEF','Roma',2,false),
    P('mmultur','M. Müldür','Mert Müldür','DEF','Fenerbahçe',17,false),
    P('calhanoglu','H. Çalhanoğlu','Hakan Çalhanoğlu','MID','Inter',10,false),
    P('okokucu','O. Kökçü','Orkun Kökçü','MID','Beşiktaş',8,false),
    P('akarazor','A. Karazor','Atakan Karazor','MID','Stuttgart',6,false),
    P('kayhan','K. Ayhan','Kaan Ayhan','MID','Galatasaray',14,false),
    P('sozcan','S. Özcan','Salih Özcan','MID','BVB',7,false),
    P('iyuksek','İ. Yüksek','İsmail Yüksek','MID','Fenerbahçe',19,false),
    P('ardaguler','A. Güler','Arda Güler','FWD','Real Madrid',11,false),
    P('kenanyildiz','K. Yıldız','Kenan Yıldız','FWD','Juventus',20,false),
    P('yunusakgun','Y. Akgün','Yunus Akgün','FWD','Galatasaray',9,false),
    P('baktürkoglu','K. Aktürkoğlu','Kerem Aktürkoğlu','FWD','Fenerbahçe',21,false),
    P('barısyilmaz','B.A. Yılmaz','Barış Alper Yılmaz','FWD','Galatasaray',26,false),

    /* ── SRB ── */
    P('rajkovic','P. Rajković','Predrag Rajković','GK','Mallorca',1,false),
    P('dmitrovic','M. Dmitrović','Marko Dmitrović','GK','Sevilla',12,false),
    P('vanja_ms','V. Milinković-Savić','Vanja Milinković-Savić','GK','Torino',23,false),
    P('milenkovic','N. Milenković','Nikola Milenković','DEF','Nottingham F.',4,false),
    P('pavlovic_s','S. Pavlović','Strahinja Pavlović','DEF','AC Milan',5,false),
    P('spajic','U. Spajić','Uroš Spajić','DEF','Anderlecht',6,false),
    P('zivkovic','A. Živković','Andrija Živković','DEF','PAOK',2,false),
    P('lazovic','D. Lazović','Darko Lazović','DEF','Hellas Verona',16,false),
    P('lukic','S. Lukić','Saša Lukić','MID','Fulham',8,false),
    P('s_milinkovic','S. Milinković-Savić','Sergej Milinković-Savić','MID','Al-Hilal',11,false),
    P('gudelj','N. Gudelj','Nemanja Gudelj','MID','Sevilla',14,false),
    P('ilic_s','S. Ilić','Sandro Ilić','MID','Lazio',17,false),
    P('tadic','D. Tadić','Dušan Tadić','MID','Fenerbahçe',10,false),
    P('kostic','F. Kostić','Filip Kostić','MID','Juventus',7,false),
    P('vlahovic','D. Vlahović','Dušan Vlahović','FWD','Juventus',9,false),
    P('jovic_l','L. Jović','Luka Jović','FWD','AC Milan',19,false),
    P('mitrovic','A. Mitrović','Aleksandar Mitrović','FWD','Al-Hilal',9,false),
    P('radonjic','N. Radonjić','Nemanja Radonjić','FWD','Torino',21,false),

    /* ── ITA ── */
    P('donnarumma','Donnarumma','Gianluigi Donnarumma','GK','PSG',1,false),
    P('meret','A. Meret','Alex Meret','GK','Napoli',12,false),
    P('vicario','G. Vicario','Guglielmo Vicario','GK','Tottenham',23,false),
    P('di_lorenzo','G. Di Lorenzo','Giovanni Di Lorenzo','DEF','Napoli',2,false),
    P('bastoni','A. Bastoni','Alessandro Bastoni','DEF','Inter',6,false),
    P('calafiori','R. Calafiori','Riccardo Calafiori','DEF','Arsenal',3,false),
    P('darmian','M. Darmian','Matteo Darmian','DEF','Inter',4,false),
    P('gatti','F. Gatti','Federico Gatti','DEF','Juventus',15,false),
    P('buongiorno','A. Buongiorno','Alessandro Buongiorno','DEF','Napoli',5,false),
    P('cambiaso','A. Cambiaso','Andrea Cambiaso','DEF','Juventus',22,false),
    P('dimarco','F. Dimarco','Federico Dimarco','DEF','Inter',17,false),
    P('barella','N. Barella','Nicolò Barella','MID','Inter',18,false),
    P('frattesi','D. Frattesi','Davide Frattesi','MID','Inter',16,false),
    P('tonali','S. Tonali','Sandro Tonali','MID','Newcastle',14,false),
    P('ricci','S. Ricci','Samuele Ricci','MID','Torino',19,false),
    P('pellegrini','L. Pellegrini','Lorenzo Pellegrini','MID','Roma',7,false),
    P('chiesa','F. Chiesa','Federico Chiesa','FWD','Liverpool',11,false),
    P('raspadori','G. Raspadori','Giacomo Raspadori','FWD','Napoli',9,false),
    P('scamacca','G. Scamacca','Gianluca Scamacca','FWD','Atalanta',21,false),
    P('zaccagni','M. Zaccagni','Mattia Zaccagni','FWD','Lazio',20,false),
    P('retegui','M. Retegui','Mateo Retegui','FWD','Atalanta',24,false),

    /* ── NIG ── */
    P('uzoho','F. Uzoho','Francis Uzoho','GK','Omonia',1,false),
    P('okoye','M. Okoye','Maduka Okoye','GK','Udinese',12,false),
    P('akpeyi','D. Akpeyi','Daniel Akpeyi','GK','Kaizer Chiefs',23,false),
    P('aina','O. Aina','Ola Aina','DEF','Nottingham F.',3,false),
    P('troost_ekong','W. Troost-Ekong','William Troost-Ekong','DEF','Al-Kholood',5,false),
    P('ajayi','S. Ajayi','Semi Ajayi','DEF','West Brom',6,false),
    P('awaziem','C. Awaziem','Chidozie Awaziem','DEF','Alanyaspor',4,false),
    P('zaidu','Z. Sanusi','Zaidu Sanusi','DEF','Porto',22,false),
    P('ndidi','W. Ndidi','Wilfred Ndidi','MID','Leicester',4,false),
    P('iwobi','A. Iwobi','Alex Iwobi','MID','Fulham',17,false),
    P('aribo','J. Aribo','Joe Aribo','MID','Southampton',8,false),
    P('etebo','O. Etebo','Oghenekaro Etebo','MID','Trabzonspor',14,false),
    P('chukwueze','S. Chukwueze','Samuel Chukwueze','FWD','AC Milan',7,false),
    P('osimhen','V. Osimhen','Victor Osimhen','FWD','Galatasaray',9,false),
    P('lookman','A. Lookman','Ademola Lookman','FWD','Atalanta',11,false),
    P('simon_m','M. Simon','Moses Simon','FWD','Nantes',10,false),
    P('awoniyi','T. Awoniyi','Taiwo Awoniyi','FWD','Nottingham F.',19,false),
    P('dessers','C. Dessers','Cyriel Dessers','FWD','Rangers',21,false),

    /* ── CAM ── */
    P('onana_a_cam','A. Onana','André Onana','GK','Man. Utd',1,false),
    P('epassy','D. Epassy','Devis Epassy','GK','Antalyaspor',16,false),
    P('ngapandouetnbu','S. Ngapandouetnbu','Simon Ngapandouetnbu','GK','Marseille',23,false),
    P('fai','C. Fai','Collins Fai','DEF','Al-Tai',2,false),
    P('castelletto','N. Castelletto','Nicolas Castelletto','DEF','Nantes',5,false),
    P('nkoulou','N. Nkoulou','Nicolas Nkoulou','DEF','Trabzonspor',4,false),
    P('tolo_e','E. Tolo','Enzo Tolo','DEF','Lens',3,false),
    P('nouhou','Nouhou','Nouhou Tolo','DEF','Seattle Sounders',22,false),
    P('mvogo_cam','B. Touré','Blati Touré','DEF','Guingamp',17,false),
    P('kunde','M. Ngadeu','Michael Ngadeu-Ngadjui','DEF','Gent',6,false),
    P('zambo','Zambo Anguissa','André-Frank Zambo Anguissa','MID','Napoli',7,false),
    P('hongla','M. Hongla','Martin Hongla','MID','Hellas Verona',15,false),
    P('ondoua','G. Ondoua','Gaël Ondoua','MID','Hannover',14,false),
    P('mbeumo','B. Mbeumo','Bryan Mbeumo','FWD','Brentford',10,false),
    P('toko_ekambi','K. Toko Ekambi','Karl Toko Ekambi','FWD','Rennes',11,false),
    P('choupo','Choupo-Moting','Eric Maxim Choupo-Moting','FWD','Al-Ittihad',9,false),
    P('aboubakar','V. Aboubakar','Vincent Aboubakar','FWD','Besiktas',8,false),
    P('bassogog','C. Bassogog','Christian Bassogog','FWD','Shanghai SH',21,false),

    /* ══════════════════════════════════════════
       GRUPO 5 (cont.) — POLONIA
    ══════════════════════════════════════════ */

    /* ── POL ── */
    P('szczesny','Szczęsny','Wojciech Szczęsny','GK','Barcelona',1,false),
    P('dragowski','Drągowski','Bartłomiej Drągowski','GK','Spezia',12,false),
    P('bulka','Bułka','Marcin Bułka','GK','Nice',23,false),
    P('bednarek','Bednarek','Jan Bednarek','DEF','Southampton',5,false),
    P('glik','Glik','Kamil Glik','DEF','Lecce',15,false),
    P('kiwior','Kiwior','Jakub Kiwior','DEF','Arsenal',4,false),
    P('cash','Cash','Matty Cash','DEF','Aston Villa',2,false),
    P('bereszynski','Bereszyński','Bartosz Bereszyński','DEF','Napoli',22,false),
    P('puchacz','Puchacz','Tymoteusz Puchacz','DEF','Union Berlin',3,false),
    P('wieteska','Wieteska','Maik Wieteska','DEF','Caen',16,false),
    P('zielinski','Zieliński','Piotr Zieliński','MID','Inter',10,false),
    P('krychowiak','Krychowiak','Grzegorz Krychowiak','MID','Al-Shabab',8,false),
    P('moder','Moder','Jakub Moder','MID','Brighton',14,false),
    P('szymanski','Szymański','Sebastian Szymański','MID','Fenerbahçe',7,false),
    P('frankowski','Frankowski','Przemysław Frankowski','MID','Lens',11,false),
    P('urbanski','Urbański','Kacper Urbański','MID','Bologna',17,false),
    P('zalewski','Zalewski','Nicola Zalewski','MID','Inter',18,false),
    P('skoras','Skóraś','Michał Skóraś','MID','Club Brugge',20,false),
    P('lewandowski','Lewandowski','Robert Lewandowski','FWD','Barcelona',9,false),
    P('piatek','Piątek','Krzysztof Piątek','FWD','Salernitana',21,false),
    P('swiderski','Świderski','Karol Świderski','FWD','Charlotte FC',19,false),
    P('buksa','Buksa','Adam Buksa','FWD','Trabzonspor',24,false),
    P('grosicki','Grosicki','Kamil Grosicki','FWD','Pogoń Szczecin',25,false),
  ];

  /* ---- Asignar campo `team` a cada jugador por orden de grupo ---- */
  (function(){
    const _r = [
      ['arg',20],['fra',18],['bra',20],['eng',19],['esp',20],['por',19],
      ['ale',18],['nld',17],['bel',17],['cro',16],
      ['usa',19],['mex',17],['can',16],['uru',16],['col',16],
      ['jpn',18],['mar',16],['sen',19],['ecu',20],
      ['kor',17],['sui',20],['den',19],['aus',18],['gha',18],
      ['tur',20],['srb',18],['ita',21],['nig',18],['cam',18],['pol',23],
    ];
    let i=0;
    for(const [team,n] of _r) for(let j=0;j<n;j++){if(players[i])players[i].team=team;i++;}
  })();

  /* ---- Picks del usuario (mock: inscripción en curso) ---- */
  const myPicks = {
    g1: ['arg','esp'],
    g2: ['ale'],
    g3: [],
    g4: [],
    g5: null,
    g6: [],
    goalscorer: { arg:'messi', esp:null },
    duo: ['mbappe', null],
  };

  /* ---- Clasificación ---- */
  const leaderboard = [
    {rank:1, name:'Laura Vidal',  user:'@lau',      pts:148, av:'LV', col:'#D8131A', trend:'+2', exact:9},
    {rank:2, name:'Diego Romero', user:'@dirom',    pts:142, av:'DR', col:'#27E5D4', trend:'-1', exact:8},
    {rank:3, name:'Marta Ibáñez', user:'@martai',   pts:139, av:'MI', col:'#8C6BFF', trend:'+1', exact:7},
    {rank:4, name:'Tú',           user:'@tucuenta', pts:131, av:'TÚ', col:'#FDD301', me:true, trend:'+3', exact:7},
    {rank:5, name:'Carlos Vega',  user:'@cvega',    pts:128, av:'CV', col:'#F79516', trend:'-2', exact:6},
    {rank:6, name:'Nuria Sanz',   user:'@nuri',     pts:124, av:'NS', col:'#ABCB2D', trend:'0',  exact:6},
    {rank:7, name:'Pablo Gil',    user:'@pgil',     pts:119, av:'PG', col:'#4DA6FF', trend:'+1', exact:5},
    {rank:8, name:'Eva Torres',   user:'@evat',     pts:115, av:'ET', col:'#FF5FA2', trend:'-1', exact:5},
    {rank:9, name:'Hugo Mora',    user:'@hugom',    pts:111, av:'HM', col:'#3DE08A', trend:'+2', exact:4},
    {rank:10,name:'Sara León',    user:'@saral',    pts:108, av:'SL', col:'#ABCB2D', trend:'-3', exact:4},
  ];

  const leagues = [
    {id:'l1', name:'Los Cracks del Finde', members:14, pot:'140 €', me:'4º', color:'#D8131A', code:'CRACK26'},
    {id:'l2', name:'Oficina FC',           members:9,  pot:'90 €',  me:'2º', color:'#27E5D4', code:'OFICFC'},
    {id:'l3', name:'Familia Vidal',        members:6,  pot:'60 €',  me:'1º', color:'#8C6BFF', code:'VIDAL26'},
  ];

  const badges = [
    {id:'b1', name:'Pleno al 15',   got:true,  col:'#FDD301', ic:'target'},
    {id:'b2', name:'Racha x5',      got:true,  col:'#D8131A', ic:'fire'},
    {id:'b3', name:'Madrugador',    got:true,  col:'#27E5D4', ic:'clock'},
    {id:'b4', name:'Top 3 jornada', got:true,  col:'#F79516', ic:'medal'},
    {id:'b5', name:'Profeta',       got:false, col:'#8C6BFF', ic:'crown'},
    {id:'b6', name:'Sin fallos',    got:false, col:'#4DA6FF', ic:'shield'},
  ];

  const bracket = {
    r16:[
      {h:'arg',a:'usa',win:'arg'}, {h:'fra',a:'mex',win:'fra'},
      {h:'esp',a:'cro',win:'esp'}, {h:'bra',a:'nld',win:'bra'},
      {h:'eng',a:'sen',win:'eng'}, {h:'por',a:'bel',win:'por'},
      {h:'ale',a:'uru',win:'ale'}, {h:'col',a:'mar',win:'mar'},
    ],
    qf:[
      {h:'arg',a:'fra',win:'arg'}, {h:'esp',a:'bra',win:'bra'},
      {h:'eng',a:'por',win:'eng'}, {h:'ale',a:'mar',win:'ale'},
    ],
    sf:[
      {h:'arg',a:'bra',win:'arg'}, {h:'eng',a:'ale',win:'eng'},
    ],
    final:[{h:'arg',a:'eng',win:'arg'}],
    champion:'arg',
  };

  const activity = [
    {who:'Diego Romero',  act:'completó su selección',     detail:'11 selecciones listas',  when:'hace 1 h', col:'#27E5D4', av:'DR'},
    {who:'Laura Vidal',   act:'actualizó su Dúo Dinámico', detail:'Mbappé + Bellingham',     when:'hace 3 h', col:'#D8131A', av:'LV'},
    {who:'Marta Ibáñez',  act:'se unió a la porra',        detail:'Los Cracks del Finde',    when:'hace 5 h', col:'#8C6BFF', av:'MI'},
  ];

  const matches = [
    {id:'m1',g:'D',home:'arg',away:'cro',date:'JUN 13',time:'21:00',venue:'MetLife · NJ',   status:'soon'},
    {id:'m2',g:'A',home:'mex',away:'nld',date:'JUN 13',time:'18:00',venue:'Azteca · CDMX',  status:'live',live:'1 - 0',min:"63'"},
    {id:'m3',g:'C',home:'usa',away:'ale',date:'JUN 14',time:'20:00',venue:'SoFi · LA',      status:'soon'},
    {id:'m4',g:'E',home:'esp',away:'uru',date:'JUN 14',time:'17:00',venue:'BC Place · VAN', status:'soon'},
    {id:'m5',g:'G',home:'bra',away:'por',date:'JUN 15',time:'21:00',venue:'AT&T · DAL',     status:'soon'},
  ];

  const deadline = new Date('2026-06-11T17:00:00');

  window.DB = {
    T, porraGroups, scoring, players, myPicks,
    leaderboard, leagues, badges, bracket, activity, matches, deadline, FLAG,
  };
})();
