/* ============================================================
   DATOS — Porra Mundial 2026
   Base de datos completa con coeficientes Transfermarkt
   ============================================================ */
(function(){
  const FLAG = (code,w=80) => `https://flagcdn.com/w${w}/${code}.png`;

  /* ----------------------------------------------------------
     BASE DE DATOS GLOBAL — todos los equipos con coeficientes
  ---------------------------------------------------------- */
  const TEAM_DB = {
    fra:{ name:'Francia',         code:'FRA', f:'fr',     coef:1877, val:1480 },
    esp:{ name:'España',          code:'ESP', f:'es',     coef:1876, val:1270 },
    arg:{ name:'Argentina',       code:'ARG', f:'ar',     coef:1875, val:816  },
    eng:{ name:'Inglaterra',      code:'ENG', f:'gb-eng', coef:1826, val:1310 },
    por:{ name:'Portugal',        code:'POR', f:'pt',     coef:1764, val:957  },
    bra:{ name:'Brasil',          code:'BRA', f:'br',     coef:1761, val:909  },
    nld:{ name:'P. Bajos',        code:'NED', f:'nl',     coef:1758, val:837  },
    mar:{ name:'Marruecos',       code:'MAR', f:'ma',     coef:1756, val:487  },
    bel:{ name:'Bélgica',         code:'BEL', f:'be',     coef:1735, val:530  },
    ale:{ name:'Alemania',        code:'ALE', f:'de',     coef:1730, val:998  },
    cro:{ name:'Croacia',         code:'CRO', f:'hr',     coef:1717, val:385  },
    ita:{ name:'Italia',          code:'ITA', f:'it',     coef:1700, val:339  },
    col:{ name:'Colombia',        code:'COL', f:'co',     coef:1693, val:305  },
    sen:{ name:'Senegal',         code:'SEN', f:'sn',     coef:1689, val:468  },
    mex:{ name:'México',          code:'MEX', f:'mx',     coef:1681, val:121  },
    usa:{ name:'EE. UU.',         code:'USA', f:'us',     coef:1673, val:367  },
    uru:{ name:'Uruguay',         code:'URU', f:'uy',     coef:1673, val:371  },
    jpn:{ name:'Japón',           code:'JPN', f:'jp',     coef:1660, val:279  },
    sui:{ name:'Suiza',           code:'SUI', f:'ch',     coef:1649, val:331  },
    den:{ name:'Dinamarca',       code:'DEN', f:'dk',     coef:1621, val:412  },
    irn:{ name:'Irán',            code:'IRN', f:'ir',     coef:1615, val:35   },
    tur:{ name:'Turquía',         code:'TUR', f:'tr',     coef:1599, val:536  },
    ecu:{ name:'Ecuador',         code:'ECU', f:'ec',     coef:1595, val:257  },
    aut:{ name:'Austria',         code:'AUT', f:'at',     coef:1593, val:271  },
    kor:{ name:'Corea S.',        code:'KOR', f:'kr',     coef:1589, val:142  },
    nig:{ name:'Nigeria',         code:'NGA', f:'ng',     coef:1585, val:62   },
    aus:{ name:'Australia',       code:'AUS', f:'au',     coef:1581, val:69   },
    alg:{ name:'Argelia',         code:'ALG', f:'dz',     coef:1564, val:226  },
    egy:{ name:'Egipto',          code:'EGY', f:'eg',     coef:1563, val:135  },
    can:{ name:'Canadá',          code:'CAN', f:'ca',     coef:1556, val:217  },
    nor:{ name:'Noruega',         code:'NOR', f:'no',     coef:1551, val:601  },
    ukr:{ name:'Ucrania',         code:'UKR', f:'ua',     coef:1547, val:267  },
    pan:{ name:'Panamá',          code:'PAN', f:'pa',     coef:1541, val:34   },
    civ:{ name:'Costa de Marfil', code:'CIV', f:'ci',     coef:1533, val:530  },
    pol:{ name:'Polonia',         code:'POL', f:'pl',     coef:1528, val:231  },
    swe:{ name:'Suecia',          code:'SWE', f:'se',     coef:1515, val:436  },
    srb:{ name:'Serbia',          code:'SRB', f:'rs',     coef:1509, val:297  },
    par:{ name:'Paraguay',        code:'PAR', f:'py',     coef:1504, val:138  },
    hun:{ name:'Hungría',         code:'HUN', f:'hu',     coef:1501, val:214  },
    cam:{ name:'Camerún',         code:'CMR', f:'cm',     coef:1481, val:200  },
    cod:{ name:'RD Congo',        code:'COD', f:'cd',     coef:1478, val:147  },
    ven:{ name:'Venezuela',       code:'VEN', f:'ve',     coef:1468, val:76   },
    mli:{ name:'Mali',            code:'MLI', f:'ml',     coef:1459, val:103  },
    per:{ name:'Perú',            code:'PER', f:'pe',     coef:1456, val:28   },
    chi:{ name:'Chile',           code:'CHI', f:'cl',     coef:1455, val:69   },
    qat:{ name:'Catar',           code:'QAT', f:'qa',     coef:1455, val:20   },
    rou:{ name:'Rumanía',         code:'ROU', f:'ro',     coef:1451, val:99   },
    svn:{ name:'Eslovenia',       code:'SVN', f:'si',     coef:1446, val:100  },
    irl:{ name:'Irlanda',         code:'IRL', f:'ie',     coef:1437, val:143  },
    rsa:{ name:'Sudáfrica',       code:'RSA', f:'za',     coef:1430, val:45   },
    ksa:{ name:'Arabia Saudita',  code:'KSA', f:'sa',     coef:1421, val:31   },
    bfa:{ name:'Burkina Faso',    code:'BFA', f:'bf',     coef:1412, val:104  },
    jor:{ name:'Jordania',        code:'JOR', f:'jo',     coef:1391, val:18   },
    alb:{ name:'Albania',         code:'ALB', f:'al',     coef:1388, val:96   },
    bih:{ name:'Bosnia',          code:'BIH', f:'ba',     coef:1386, val:147  },
    hon:{ name:'Honduras',        code:'HON', f:'hn',     coef:1380, val:17   },
    jam:{ name:'Jamaica',         code:'JAM', f:'jm',     coef:1358, val:9    },
    geo:{ name:'Georgia',         code:'GEO', f:'ge',     coef:1350, val:198  },
    gha:{ name:'Ghana',           code:'GHA', f:'gh',     coef:1346, val:234  },
    isl:{ name:'Islandia',        code:'ISL', f:'is',     coef:1345, val:78   },
    tun:{ name:'Túnez',           code:'TUN', f:'tn',     coef:1542, val:185  },
    sco:{ name:'Escocia',         code:'SCO', f:'gb-sct', coef:1478, val:175  },
    cze:{ name:'Rep. Checa',      code:'CZE', f:'cz',     coef:1487, val:220  },
    irq:{ name:'Irak',            code:'IRQ', f:'iq',     coef:1318, val:55   },
    nzl:{ name:'Nueva Zelanda',   code:'NZL', f:'nz',     coef:1265, val:48   },
    cur:{ name:'Curazao',         code:'CUR', f:'cw',     coef:1248, val:28   },
    cpv:{ name:'Cabo Verde',      code:'CPV', f:'cv',     coef:1372, val:75   },
    uzb:{ name:'Uzbekistán',      code:'UZB', f:'uz',     coef:1398, val:65   },
    hai:{ name:'Haití',           code:'HAI', f:'ht',     coef:1255, val:22   },
  };

  Object.keys(TEAM_DB).forEach(k => {
    TEAM_DB[k].id    = k;
    TEAM_DB[k].flag  = FLAG(TEAM_DB[k].f);
    TEAM_DB[k].flagHi = FLAG(TEAM_DB[k].f, 160);
  });

  /* ----------------------------------------------------------
     HELPERS DE DRAFT
  ---------------------------------------------------------- */
  function getTeamsByCoef() {
    return Object.values(TEAM_DB).sort((a,b) => b.coef - a.coef);
  }

  function autoAssignDraft(selectedIds, groupConfig) {
    const sorted = [...selectedIds].sort((a,b) => (TEAM_DB[b]?.coef||0) - (TEAM_DB[a]?.coef||0));
    const result = {};
    groupConfig.forEach(g => result[g.id] = []);
    let pos = 0;
    for (const g of groupConfig) {
      const take = g.targetSize || 4;
      result[g.id] = sorted.slice(pos, pos + take);
      pos += take;
    }
    return result;
  }

  /* ----------------------------------------------------------
     GRUPOS DE LA PORRA (partida activa)
  ---------------------------------------------------------- */
  const porraGroups = [
    { id:1, name:'La Grasa Papa',      emoji:'🏆', pick:2, targetSize:8,  multiplier:1,
      teams:['esp','eng','bra','por','arg','fra','ale','nld'] },
    { id:2, name:'¿Por qué no?',       emoji:'🌍', pick:2, targetSize:10, multiplier:1,
      teams:['col','mar','bel','sui','nor','tur','uru','swe','cro','sen'] },
    { id:3, name:'Party Fiesta',       emoji:'🎉', pick:2, targetSize:8,  multiplier:1,
      teams:['jpn','can','mex','aut','usa','bih','ecu','cze'] },
    { id:4, name:'Wakanda For Ever',   emoji:'⚔️',  pick:2, targetSize:7,  multiplier:1,
      teams:['civ','tun','egy','rsa','gha','cod','alg'] },
    { id:5, name:'Relleno Mundialero', emoji:'🎲', pick:1, targetSize:6,  multiplier:2.5,
      teams:['sco','aus','par','ksa','kor','qat'] },
    { id:6, name:'Vinieron a fichar',  emoji:'✈️',  pick:2, targetSize:9,  multiplier:2,
      teams:['irq','jor','nzl','cur','pan','cpv','irn','uzb','hai'] },
  ];

  const T = TEAM_DB;

  /* ----------------------------------------------------------
     PUNTUACIÓN
  ---------------------------------------------------------- */
  const scoring = {
    price: 10,
    groupPhase: { win:3, draw:1, loss:0, first:5, second:3 },
    knockouts:  { r32:3, r16:5, qf:8, sf:10, final:15, champ:20 },
    goalscorer: { one:5, both:10 },
    g5Multiplier: 2.5,
  };

  /* ----------------------------------------------------------
     JUGADORES — Plantillas oficiales Mundial 2026
     g1:true = del Grupo 1 (La Grasa Papa)
  ---------------------------------------------------------- */
  const _P = (id,name,fullName,pos,club,num,team,g1)=>
    ({id,name,fullName,pos,club,num,team,g1,goals:0,assists:0});

  const players = [
    /* ── ARG (G1) ── */
    _P('arg_emartinez','E. Martínez','Emiliano Martínez','GK','Aston Villa',1,'arg',true),
    _P('arg_musso','J. Musso','Juan Musso','GK','Atlético Madrid',12,'arg',true),
    _P('arg_rulli','G. Rulli','Gerónimo Rulli','GK','Marseille',23,'arg',true),
    _P('arg_balerdi','L. Balerdi','Leonardo Balerdi','DEF','Marseille',4,'arg',true),
    _P('arg_lisandro','Lisandro','Lisandro Martínez','DEF','Man. Utd',6,'arg',true),
    _P('arg_medina','F. Medina','Facundo Medina','DEF','Marseille',5,'arg',true),
    _P('arg_molina','N. Molina','Nahuel Molina','DEF','Atlético Madrid',26,'arg',true),
    _P('arg_montiel','G. Montiel','Gonzalo Montiel','DEF','River Plate',2,'arg',true),
    _P('arg_otamendi','Otamendi','Nicolás Otamendi','DEF','Benfica',19,'arg',true),
    _P('arg_romero','C. Romero','Cristian Romero','DEF','Tottenham',13,'arg',true),
    _P('arg_tagliafico','N. Tagliafico','Nicolás Tagliafico','DEF','Lyon',3,'arg',true),
    _P('arg_barco','V. Barco','Valentín Barco','MID','Strasbourg',17,'arg',true),
    _P('arg_depaul','R. De Paul','Rodrigo De Paul','MID','Inter Miami',7,'arg',true),
    _P('arg_enzo','E. Fernández','Enzo Fernández','MID','Chelsea',24,'arg',true),
    _P('arg_locelso','G. Lo Celso','Giovani Lo Celso','MID','Real Betis',16,'arg',true),
    _P('arg_macallister','A. Mac Allister','Alexis Mac Allister','MID','Liverpool',10,'arg',true),
    _P('arg_palacios','E. Palacios','Exequiel Palacios','MID','Leverkusen',14,'arg',true),
    _P('arg_paredes','L. Paredes','Leandro Paredes','MID','Boca Juniors',5,'arg',true),
    _P('arg_almada','T. Almada','Thiago Almada','FWD','Atlético Madrid',17,'arg',true),
    _P('arg_julian','J. Álvarez','Julián Álvarez','FWD','Atlético Madrid',9,'arg',true),
    _P('arg_ngonzalez','N. González','Nicolás González','FWD','Atlético Madrid',11,'arg',true),
    _P('arg_jmlopez','J.M. López','José Manuel López','FWD','Palmeiras',22,'arg',true),
    _P('arg_lautaro','Lautaro','Lautaro Martínez','FWD','Inter',20,'arg',true),
    _P('arg_messi','L. Messi','Lionel Messi','FWD','Inter Miami',10,'arg',true),
    _P('arg_paz','N. Paz','Nicolás Paz','FWD','Como',21,'arg',true),
    _P('arg_gsimeone','G. Simeone','Giuliano Simeone','FWD','Atlético Madrid',25,'arg',true),
    /* ── FRA (G1) ── */
    _P('fra_maignan','M. Maignan','Mike Maignan','GK','AC Milan',1,'fra',true),
    _P('fra_risser','R. Risser','Robin Risser','GK','Lens',12,'fra',true),
    _P('fra_samba','B. Samba','Brice Samba','GK','Rennes',23,'fra',true),
    _P('fra_digne','L. Digne','Lucas Digne','DEF','Aston Villa',12,'fra',true),
    _P('fra_gusto','M. Gusto','Malo Gusto','DEF','Chelsea',2,'fra',true),
    _P('fra_lhernandez','L. Hernández','Lucas Hernández','DEF','PSG',21,'fra',true),
    _P('fra_theo','T. Hernández','Theo Hernández','DEF','Al Hilal',22,'fra',true),
    _P('fra_konate','I. Konaté','Ibrahima Konaté','DEF','Liverpool',4,'fra',true),
    _P('fra_kounde','J. Koundé','Jules Koundé','DEF','Barcelona',5,'fra',true),
    _P('fra_lacroix','M. Lacroix','Maxence Lacroix','DEF','Crystal Palace',3,'fra',true),
    _P('fra_saliba','W. Saliba','William Saliba','DEF','Arsenal',17,'fra',true),
    _P('fra_upamecano','D. Upamecano','Dayot Upamecano','DEF','Bayern',6,'fra',true),
    _P('fra_kante','N. Kanté','N\'Golo Kanté','MID','Fenerbahçe',7,'fra',true),
    _P('fra_kone','M. Koné','Manu Koné','MID','AS Roma',6,'fra',true),
    _P('fra_rabiot','A. Rabiot','Adrien Rabiot','MID','AC Milan',14,'fra',true),
    _P('fra_tchouameni','A. Tchouaméni','Aurélien Tchouaméni','MID','Real Madrid',8,'fra',true),
    _P('fra_zaire_emery','W. Zaïre-Emery','Warren Zaïre-Emery','MID','PSG',17,'fra',true),
    _P('fra_akliouche','M. Akliouche','Maghnes Akliouche','FWD','Monaco',20,'fra',true),
    _P('fra_barcola','B. Barcola','Bradley Barcola','FWD','PSG',11,'fra',true),
    _P('fra_cherki','R. Cherki','Rayan Cherki','FWD','Man. City',19,'fra',true),
    _P('fra_dembele','O. Dembélé','Ousmane Dembélé','FWD','PSG',10,'fra',true),
    _P('fra_doue','D. Doué','Désiré Doué','FWD','PSG',18,'fra',true),
    _P('fra_mateta','J-P. Mateta','Jean-Philippe Mateta','FWD','Crystal Palace',9,'fra',true),
    _P('fra_mbappe','K. Mbappé','Kylian Mbappé','FWD','Real Madrid',10,'fra',true),
    _P('fra_olise','M. Olise','Michael Olise','FWD','Bayern',25,'fra',true),
    _P('fra_thuram','M. Thuram','Marcus Thuram','FWD','Inter',15,'fra',true),
    /* ── BRA (G1) ── */
    _P('bra_alisson','Alisson','Alisson Becker','GK','Liverpool',1,'bra',true),
    _P('bra_ederson','Ederson','Ederson Moraes','GK','Fenerbahçe',12,'bra',true),
    _P('bra_weverton','Weverton','Weverton Pereira','GK','Grêmio',23,'bra',true),
    _P('bra_marquinhos','Marquinhos','Marquinhos','DEF','PSG',5,'bra',true),
    _P('bra_gabriel','G. Magalhães','Gabriel Magalhães','DEF','Arsenal',4,'bra',true),
    _P('bra_bremer','Bremer','Gleison Bremer','DEF','Juventus',3,'bra',true),
    _P('bra_ibanez','Ibañez','Arthur Ibañez','DEF','Al Ahli',6,'bra',true),
    _P('bra_leopereira','L. Pereira','Léo Pereira','DEF','Flamengo',15,'bra',true),
    _P('bra_wesley','Wesley','Wesley Gassova','DEF','Roma',2,'bra',true),
    _P('bra_danilo','Danilo','Danilo Luiz','DEF','Flamengo',13,'bra',true),
    _P('bra_alexsandro','Alex Sandro','Alex Sandro','DEF','Flamengo',6,'bra',true),
    _P('bra_dsantos','D. Santos','Douglas Santos','DEF','Zenit',16,'bra',true),
    _P('bra_casemiro','Casemiro','Carlos Henrique Casemiro','MID','Man. Utd',5,'bra',true),
    _P('bra_brunog','B. Guimarães','Bruno Guimarães','MID','Newcastle',8,'bra',true),
    _P('bra_fabinho','Fabinho','Fabinho','MID','Al Ittihad',7,'bra',true),
    _P('bra_danilo_mid','Danilo (MID)','Danilo de Abreu','MID','Botafogo',11,'bra',true),
    _P('bra_paqueta','L. Paquetá','Lucas Paquetá','MID','Flamengo',10,'bra',true),
    _P('bra_vinicius','Vinícius Jr.','Vinícius Júnior','FWD','Real Madrid',7,'bra',true),
    _P('bra_raphinha','Raphinha','Raphinha','FWD','Barcelona',17,'bra',true),
    _P('bra_cunha','M. Cunha','Matheus Cunha','FWD','Man. Utd',9,'bra',true),
    _P('bra_luizhenrique','L. Henrique','Luiz Henrique','FWD','Zenit',19,'bra',true),
    _P('bra_igorthiago','I. Thiago','Igor Thiago','FWD','Brentford',22,'bra',true),
    _P('bra_endrick','Endrick','Endrick Felipe','FWD','Real Madrid',16,'bra',true),
    _P('bra_martinelli','G. Martinelli','Gabriel Martinelli','FWD','Arsenal',11,'bra',true),
    _P('bra_rayan','Rayan','Rayan','FWD','Bournemouth',26,'bra',true),
    _P('bra_neymar','Neymar','Neymar Jr.','FWD','Santos',10,'bra',true),
    /* ── ENG (G1) ── */
    _P('eng_pickford','J. Pickford','Jordan Pickford','GK','Everton',1,'eng',true),
    _P('eng_henderson_d','D. Henderson','Dean Henderson','GK','Crystal Palace',12,'eng',true),
    _P('eng_trafford','J. Trafford','James Trafford','GK','Man. City',23,'eng',true),
    _P('eng_rjames','R. James','Reece James','DEF','Chelsea',2,'eng',true),
    _P('eng_konsa','E. Konsa','Ezri Konsa','DEF','Aston Villa',4,'eng',true),
    _P('eng_quansah','J. Quansah','Jarell Quansah','DEF','Leverkusen',5,'eng',true),
    _P('eng_stones','J. Stones','John Stones','DEF','Man. City',6,'eng',true),
    _P('eng_guehi','M. Guehi','Marc Guehi','DEF','Man. City',3,'eng',true),
    _P('eng_burn','D. Burn','Dan Burn','DEF','Newcastle',22,'eng',true),
    _P('eng_oreilly','N. O\'Reilly','Nico O\'Reilly','DEF','Man. City',21,'eng',true),
    _P('eng_spence','D. Spence','Djed Spence','DEF','Tottenham',15,'eng',true),
    _P('eng_livramento','T. Livramento','Tino Livramento','DEF','Newcastle',25,'eng',true),
    _P('eng_rice','D. Rice','Declan Rice','MID','Arsenal',41,'eng',true),
    _P('eng_anderson','E. Anderson','Elliot Anderson','MID','Nottingham F.',16,'eng',true),
    _P('eng_mainoo','K. Mainoo','Kobbie Mainoo','MID','Man. Utd',26,'eng',true),
    _P('eng_jhenderson','J. Henderson','Jordan Henderson','MID','Brentford',8,'eng',true),
    _P('eng_rogers','M. Rogers','Morgan Rogers','MID','Aston Villa',14,'eng',true),
    _P('eng_bellingham','J. Bellingham','Jude Bellingham','MID','Real Madrid',10,'eng',true),
    _P('eng_eze','E. Eze','Eberechi Eze','MID','Arsenal',19,'eng',true),
    _P('eng_kane','H. Kane','Harry Kane','FWD','Bayern',9,'eng',true),
    _P('eng_toney','I. Toney','Ivan Toney','FWD','Al Ahli',18,'eng',true),
    _P('eng_watkins','O. Watkins','Ollie Watkins','FWD','Aston Villa',11,'eng',true),
    _P('eng_saka','B. Saka','Bukayo Saka','FWD','Arsenal',7,'eng',true),
    _P('eng_rashford','M. Rashford','Marcus Rashford','FWD','Barcelona',11,'eng',true),
    _P('eng_gordon','A. Gordon','Anthony Gordon','FWD','Barcelona',17,'eng',true),
    _P('eng_madueke','N. Madueke','Noni Madueke','FWD','Arsenal',20,'eng',true),
    /* ── ESP (G1) ── */
    _P('esp_simon','U. Simón','Unai Simón','GK','Athletic Club',1,'esp',true),
    _P('esp_raya','D. Raya','David Raya','GK','Arsenal',13,'esp',true),
    _P('esp_jgarcia','J. García','Joan García','GK','Barcelona',23,'esp',true),
    _P('esp_laporte','A. Laporte','Aymeric Laporte','DEF','Athletic Club',14,'esp',true),
    _P('esp_cucurella','M. Cucurella','Marc Cucurella','DEF','Chelsea',18,'esp',true),
    _P('esp_llorente','M. Llorente','Marcos Llorente','DEF','Atlético Madrid',16,'esp',true),
    _P('esp_egarcia','E. García','Eric García','DEF','Barcelona',3,'esp',true),
    _P('esp_porro','P. Porro','Pedro Porro','DEF','Tottenham',2,'esp',true),
    _P('esp_grimaldo','Á. Grimaldo','Alejandro Grimaldo','DEF','Leverkusen',6,'esp',true),
    _P('esp_cubarsi','P. Cubarsí','Pau Cubarsí','DEF','Barcelona',5,'esp',true),
    _P('esp_pubill','M. Pubill','Marc Pubill','DEF','Atlético Madrid',22,'esp',true),
    _P('esp_rodri','Rodri','Rodri Hernández','MID','Man. City',16,'esp',true),
    _P('esp_fabian','F. Ruiz','Fabián Ruiz','MID','PSG',4,'esp',true),
    _P('esp_merino','M. Merino','Mikel Merino','MID','Arsenal',8,'esp',true),
    _P('esp_pedri','Pedri','Pedro González López','MID','Barcelona',26,'esp',true),
    _P('esp_gavi','Gavi','Pablo Gavi','MID','Barcelona',9,'esp',true),
    _P('esp_zubimendi','M. Zubimendi','Martín Zubimendi','MID','Arsenal',20,'esp',true),
    _P('esp_baena','A. Baena','Alex Baena','MID','Atlético Madrid',17,'esp',true),
    _P('esp_torres','F. Torres','Ferran Torres','FWD','Barcelona',11,'esp',true),
    _P('esp_oyarzabal','M. Oyarzabal','Mikel Oyarzabal','FWD','Real Sociedad',21,'esp',true),
    _P('esp_olmo','D. Olmo','Dani Olmo','FWD','Barcelona',7,'esp',true),
    _P('esp_williams','N. Williams','Nico Williams','FWD','Athletic Club',17,'esp',true),
    _P('esp_yamal','L. Yamal','Lamine Yamal','FWD','Barcelona',19,'esp',true),
    _P('esp_pino','Y. Pino','Yeremy Pino','FWD','Crystal Palace',24,'esp',true),
    _P('esp_borja','B. Iglesias','Borja Iglesias','FWD','Celta Vigo',9,'esp',true),
    _P('esp_vmunoz','V. Muñoz','Víctor Muñoz','FWD','Osasuna',25,'esp',true),
    /* ── POR (G1) ── */
    _P('por_dcosta','D. Costa','Diogo Costa','GK','Porto',1,'por',true),
    _P('por_jsa','J. Sá','José Sá','GK','Wolverhampton',12,'por',true),
    _P('por_rsilva','R. Silva','Rui Silva','GK','Sporting',23,'por',true),
    _P('por_dalot','D. Dalot','Diogo Dalot','DEF','Man. Utd',2,'por',true),
    _P('por_mnunes','M. Nunes','Matheus Nunes','DEF','Man. City',4,'por',true),
    _P('por_semedo','N. Semedo','Nélson Semedo','DEF','Fenerbahçe',22,'por',true),
    _P('por_cancelo','J. Cancelo','João Cancelo','DEF','Barcelona',20,'por',true),
    _P('por_nmendes','N. Mendes','Nuno Mendes','DEF','PSG',25,'por',true),
    _P('por_ginacio','G. Inácio','Gonçalo Inácio','DEF','Sporting',3,'por',true),
    _P('por_rveiga','R. Veiga','Renato Veiga','DEF','Villarreal',5,'por',true),
    _P('por_rdias','R. Dias','Rúben Dias','DEF','Man. City',6,'por',true),
    _P('por_taraujo','T. Araújo','Tomás Araújo','DEF','Benfica',15,'por',true),
    _P('por_rneves','R. Neves','Rúben Neves','MID','Al Hilal',8,'por',true),
    _P('por_scosta','S. Costa','Samuel Costa','MID','Mallorca',16,'por',true),
    _P('por_jneves','J. Neves','João Neves','MID','PSG',17,'por',true),
    _P('por_vitinha','Vitinha','Vítor Ferreira','MID','PSG',11,'por',true),
    _P('por_bfernandes','B. Fernandes','Bruno Fernandes','MID','Man. Utd',8,'por',true),
    _P('por_bernardo','B. Silva','Bernardo Silva','MID','Man. City',10,'por',true),
    _P('por_felix','J. Félix','João Félix','FWD','Al Nassr',9,'por',true),
    _P('por_trincao','F. Trincão','Francisco Trincão','FWD','Sporting',21,'por',true),
    _P('por_fconceicao','F. Conceição','Francisco Conceição','FWD','Juventus',20,'por',true),
    _P('por_pneto','P. Neto','Pedro Neto','FWD','Chelsea',7,'por',true),
    _P('por_leao','R. Leão','Rafael Leão','FWD','AC Milan',17,'por',true),
    _P('por_gguedes','G. Guedes','Gonçalo Guedes','FWD','Real Sociedad',18,'por',true),
    _P('por_gramos','G. Ramos','Gonçalo Ramos','FWD','PSG',19,'por',true),
    _P('por_ronaldo','C. Ronaldo','Cristiano Ronaldo','FWD','Al Nassr',7,'por',true),
    _P('por_rvelho','R. Velho','Ricardo Velho','GK','Gençlerbirligi',24,'por',true),
    /* ── ALE (G1) ── */
    _P('ale_neuer','M. Neuer','Manuel Neuer','GK','Bayern',1,'ale',true),
    _P('ale_baumann','O. Baumann','Oliver Baumann','GK','Hoffenheim',12,'ale',true),
    _P('ale_nubel','A. Nübel','Alexander Nübel','GK','Bayern',23,'ale',true),
    _P('ale_anton','W. Anton','Waldemar Anton','DEF','BVB',5,'ale',true),
    _P('ale_brown','N. Brown','Nathaniel Brown','DEF','Frankfurt',15,'ale',true),
    _P('ale_raum','D. Raum','David Raum','DEF','Leipzig',6,'ale',true),
    _P('ale_rudiger','A. Rüdiger','Antonio Rüdiger','DEF','Real Madrid',2,'ale',true),
    _P('ale_schlotterbeck','N. Schlotterbeck','Nico Schlotterbeck','DEF','BVB',4,'ale',true),
    _P('ale_tah','J. Tah','Jonathan Tah','DEF','Bayern',3,'ale',true),
    _P('ale_thiaw','M. Thiaw','Malick Thiaw','DEF','Newcastle',16,'ale',true),
    _P('ale_gross','P. Groß','Pascal Groß','MID','Brighton',8,'ale',true),
    _P('ale_kimmich','J. Kimmich','Joshua Kimmich','MID','Bayern',6,'ale',true),
    _P('ale_nmecha','F. Nmecha','Felix Nmecha','MID','BVB',17,'ale',true),
    _P('ale_pavlovic','A. Pavlovic','Aleksandar Pavlovic','MID','Bayern',14,'ale',true),
    _P('ale_stiller','A. Stiller','Angelo Stiller','MID','Stuttgart',21,'ale',true),
    _P('ale_goretzka','L. Goretzka','Leon Goretzka','MID','Bayern',18,'ale',true),
    _P('ale_wirtz','F. Wirtz','Florian Wirtz','MID','Liverpool',11,'ale',true),
    _P('ale_leweling','J. Leweling','Jamie Leweling','MID','Stuttgart',20,'ale',true),
    _P('ale_beier','M. Beier','Maximilian Beier','FWD','BVB',19,'ale',true),
    _P('ale_havertz','K. Havertz','Kai Havertz','FWD','Arsenal',7,'ale',true),
    _P('ale_lkarl','L. Karl','Lennart Karl','FWD','Bayern',22,'ale',true),
    _P('ale_musiala','J. Musiala','Jamal Musiala','FWD','Bayern',10,'ale',true),
    _P('ale_sane','L. Sané','Leroy Sané','FWD','Galatasaray',13,'ale',true),
    _P('ale_undav','D. Undav','Deniz Undav','FWD','Stuttgart',9,'ale',true),
    _P('ale_woltemade','N. Woltemade','Nick Woltemade','FWD','Newcastle',25,'ale',true),
    /* ── NLD (G1) ── */
    _P('nld_verbruggen','B. Verbruggen','Bart Verbruggen','GK','Brighton',1,'nld',true),
    _P('nld_flekken','M. Flekken','Mark Flekken','GK','Leverkusen',12,'nld',true),
    _P('nld_roefs','R. Roefs','Robin Roefs','GK','Sunderland',23,'nld',true),
    _P('nld_vandijk','V. van Dijk','Virgil van Dijk','DEF','Liverpool',4,'nld',true),
    _P('nld_vanheck','J.P. van Hecke','Jan Paul van Hecke','DEF','Brighton',3,'nld',true),
    _P('nld_ake','N. Aké','Nathan Aké','DEF','Man. City',5,'nld',true),
    _P('nld_vandeVen','M. van de Ven','Micky van de Ven','DEF','Tottenham',6,'nld',true),
    _P('nld_dumfries','D. Dumfries','Denzel Dumfries','DEF','Inter',2,'nld',true),
    _P('nld_hato','J. Hato','Jorrel Hato','DEF','Chelsea',22,'nld',true),
    _P('nld_timber','J. Timber','Jurriën Timber','DEF','Arsenal',21,'nld',true),
    _P('nld_dejong','F. de Jong','Frenkie de Jong','MID','Barcelona',8,'nld',true),
    _P('nld_reijnders','T. Reijnders','Tijjani Reijnders','MID','Man. City',14,'nld',true),
    _P('nld_jkluivert','J. Kluivert','Justin Kluivert','MID','Bournemouth',10,'nld',true),
    _P('nld_qtimber','Q. Timber','Quinten Timber','MID','Marseille',16,'nld',true),
    _P('nld_koopmeiners','T. Koopmeiners','Teun Koopmeiners','MID','Juventus',17,'nld',true),
    _P('nld_gravenberch','R. Gravenberch','Ryan Gravenberch','MID','Liverpool',7,'nld',true),
    _P('nld_deroon','M. de Roon','Marten de Roon','MID','Atalanta',15,'nld',true),
    _P('nld_til','G. Til','Guus Til','MID','PSV',18,'nld',true),
    _P('nld_weiffer','M. Weiffer','Mats Weiffer','MID','Brighton',19,'nld',true),
    _P('nld_gakpo','C. Gakpo','Cody Gakpo','FWD','Liverpool',11,'nld',true),
    _P('nld_malen','D. Malén','Donyell Malén','FWD','Roma',7,'nld',true),
    _P('nld_brobbey','B. Brobbey','Brian Brobbey','FWD','Sunderland',9,'nld',true),
    _P('nld_lang','N. Lang','Noa Lang','FWD','Galatasaray',20,'nld',true),
    _P('nld_depay','M. Depay','Memphis Depay','FWD','Corinthians',10,'nld',true),
    _P('nld_weghorst','W. Weghorst','Wout Weghorst','FWD','Ajax',19,'nld',true),
    _P('nld_summerville','C. Summerville','Crysencio Summerville','FWD','West Ham',25,'nld',true),
    /* ── COL (G2) ── */
    _P('col_vargas','C. Vargas','Camilo Vargas','GK','Atlas',1,'col',false),
    _P('col_montero','Á. Montero','Álvaro Montero','GK','Vélez',12,'col',false),
    _P('col_ospina','D. Ospina','David Ospina','GK','Atl. Nacional',23,'col',false),
    _P('col_davinson','D. Sánchez','Davinson Sánchez','DEF','Galatasaray',4,'col',false),
    _P('col_lucumi','J. Lucumí','Jhon Lucumí','DEF','Bologna',5,'col',false),
    _P('col_mina','Y. Mina','Yerry Mina','DEF','Cagliari',13,'col',false),
    _P('col_munoz','D. Muñoz','Daniel Muñoz','DEF','Crystal Palace',2,'col',false),
    _P('col_mojica','J. Mojica','Johan Mojica','DEF','Mallorca',3,'col',false),
    _P('col_rios','R. Ríos','Richard Ríos','MID','Benfica',16,'col',false),
    _P('col_lerma','J. Lerma','Jefferson Lerma','MID','Crystal Palace',8,'col',false),
    _P('col_arias','J. Arias','Jhon Arias','MID','Palmeiras',11,'col',false),
    _P('col_james','J. Rodríguez','James Rodríguez','MID','Minnesota Utd',10,'col',false),
    _P('col_quintero','J.F. Quintero','Juan Fernando Quintero','MID','River Plate',9,'col',false),
    _P('col_diaz','L. Díaz','Luis Díaz','FWD','Bayern',23,'col',false),
    _P('col_hernandez','J.C. Hernández','Juan Camilo Hernández','FWD','Real Betis',7,'col',false),
    _P('col_cordoba','J. Córdoba','Jhon Córdoba','FWD','Krasnodar',19,'col',false),
    /* ── MAR (G2) ── */
    _P('mar_bounou','Y. Bounou','Yassine Bounou','GK','Al Hilal',1,'mar',false),
    _P('mar_tagnaouti','A. Tagnaouti','Ahmed Tagnaouti','GK','Forces Armées',12,'mar',false),
    _P('mar_hakimi','A. Hakimi','Achraf Hakimi','DEF','PSG',2,'mar',false),
    _P('mar_mazraoui','N. Mazraoui','Noussair Mazraoui','DEF','Man. Utd',22,'mar',false),
    _P('mar_aguerd','N. Aguerd','Nayef Aguerd','DEF','Marseille',4,'mar',false),
    _P('mar_amrabat','S. Amrabat','Sofyan Amrabat','MID','Real Betis',6,'mar',false),
    _P('mar_ounahi','A. Ounahi','Azzedine Ounahi','MID','Girona',8,'mar',false),
    _P('mar_elkhannouss','B. El Khannous','Bilal El Khannous','MID','Stuttgart',10,'mar',false),
    _P('mar_brahim','B. Díaz','Brahim Díaz','FWD','Real Madrid',11,'mar',false),
    _P('mar_ezzalzouli','A. Ezzalzouli','Abdessamad Ezzalzouli','FWD','Real Betis',19,'mar',false),
    _P('mar_elkaabi','A. El Kaabi','Ayoub El Kaabi','FWD','Olympiacos',9,'mar',false),
    _P('mar_rahimi','S. Rahimi','Soufiane Rahimi','FWD','Al Ain',7,'mar',false),
    /* ── BEL (G2) ── */
    _P('bel_courtois','T. Courtois','Thibaut Courtois','GK','Real Madrid',1,'bel',false),
    _P('bel_lammens','S. Lammens','Senne Lammens','GK','Man. Utd',12,'bel',false),
    _P('bel_castagne','T. Castagne','Timothy Castagne','DEF','Fulham',22,'bel',false),
    _P('bel_debast','Z. Debast','Zeno Debast','DEF','Sporting',2,'bel',false),
    _P('bel_decuyper','M. De Cuyper','Maxim De Cuyper','DEF','Brighton',3,'bel',false),
    _P('bel_theate','A. Theate','Arthur Theate','DEF','Frankfurt',4,'bel',false),
    _P('bel_debruyne','K. De Bruyne','Kevin De Bruyne','MID','Nápoles',7,'bel',false),
    _P('bel_onana','A. Onana','Amadou Onana','MID','Aston Villa',8,'bel',false),
    _P('bel_tielemans','Y. Tielemans','Youri Tielemans','MID','Aston Villa',14,'bel',false),
    _P('bel_saelemaekers','A. Saelemaekers','Alexis Saelemaekers','MID','AC Milan',11,'bel',false),
    _P('bel_lukaku','R. Lukaku','Romelu Lukaku','FWD','Nápoles',9,'bel',false),
    _P('bel_doku','J. Doku','Jérémy Doku','FWD','Man. City',16,'bel',false),
    _P('bel_trossard','L. Trossard','Leandro Trossard','FWD','Arsenal',17,'bel',false),
    _P('bel_deketelaere','C. De Ketelaere','Charles De Ketelaere','FWD','Atalanta',10,'bel',false),
    /* ── SUI (G2) ── */
    _P('sui_kobel','G. Kobel','Gregor Kobel','GK','BVB',1,'sui',false),
    _P('sui_mvogo','Y. Mvogo','Yvon Mvogo','GK','Lorient',12,'sui',false),
    _P('sui_akanji','M. Akanji','Manuel Akanji','DEF','Inter',5,'sui',false),
    _P('sui_amenda','A. Amenda','Aurèle Amenda','DEF','Frankfurt',6,'sui',false),
    _P('sui_elvedi','N. Elvedi','Nico Elvedi','DEF','Gladbach',3,'sui',false),
    _P('sui_rodriguez','R. Rodríguez','Ricardo Rodríguez','DEF','Real Betis',13,'sui',false),
    _P('sui_widmer','S. Widmer','Silvan Widmer','DEF','Mainz',2,'sui',false),
    _P('sui_xhaka','G. Xhaka','Granit Xhaka','MID','Sunderland',10,'sui',false),
    _P('sui_freuler','R. Freuler','Remo Freuler','MID','Bologna',8,'sui',false),
    _P('sui_jashari','A. Jashari','Ardon Jashari','MID','AC Milan',16,'sui',false),
    _P('sui_aebischer','M. Aebischer','Michel Aebischer','MID','Pisa',17,'sui',false),
    _P('sui_rvargas','R. Vargas','Ruben Vargas','MID','Sevilla',11,'sui',false),
    _P('sui_embolo','B. Embolo','Breel Embolo','FWD','Rennes',7,'sui',false),
    _P('sui_amdouni','Z. Amdouni','Zeki Amdouni','FWD','Burnley',9,'sui',false),
    _P('sui_ndoye','D. Ndoye','Dan Ndoye','FWD','Nottingham F.',18,'sui',false),
    _P('sui_okafor','N. Okafor','Noah Okafor','FWD','Leeds',22,'sui',false),
    /* ── NOR (G2) ── */
    _P('nor_nyland','Ø. Nyland','Ørjan Nyland','GK','Sevilla',1,'nor',false),
    _P('nor_odegaard','M. Ødegaard','Martin Ødegaard','MID','Arsenal',8,'nor',false),
    _P('nor_haaland','E. Haaland','Erling Haaland','FWD','Man. City',9,'nor',false),
    _P('nor_sorloth','A. Sørloth','Alexander Sørloth','FWD','Atlético Madrid',11,'nor',false),
    _P('nor_thorstvedt','K. Thorstvedt','Kristian Thorstvedt','MID','Sassuolo',10,'nor',false),
    _P('nor_berge','S. Berge','Sander Berge','MID','Fulham',6,'nor',false),
    _P('nor_nusa','A. Nusa','Antonio Nusa','FWD','Leipzig',21,'nor',false),
    _P('nor_strandlarsen','J.S. Larsen','Jørgen Strand Larsen','FWD','Crystal Palace',19,'nor',false),
    _P('nor_ryerson','J. Ryerson','Julian Ryerson','DEF','BVB',2,'nor',false),
    /* ── TUR (G2) ── */
    _P('tur_cakir','U. Çakır','Uğurcan Çakır','GK','Galatasaray',1,'tur',false),
    _P('tur_bayindir','A. Bayındır','Altay Bayındır','GK','Man. Utd',23,'tur',false),
    _P('tur_gunok','M. Günok','Mert Günok','GK','Beşiktaş',12,'tur',false),
    _P('tur_kadioglu','F. Kadıoğlu','Ferdi Kadıoğlu','DEF','Brighton',3,'tur',false),
    _P('tur_demiral','M. Demiral','Merih Demiral','DEF','Al Ahli',5,'tur',false),
    _P('tur_celik','Z. Çelik','Zeki Çelik','DEF','Roma',2,'tur',false),
    _P('tur_bardakci','A. Bardakcı','Abdülkerim Bardakcı','DEF','Galatasaray',4,'tur',false),
    _P('tur_calhanoglu','H. Çalhanoğlu','Hakan Çalhanoğlu','MID','Inter',10,'tur',false),
    _P('tur_guler','A. Güler','Arda Güler','MID','Real Madrid',11,'tur',false),
    _P('tur_uzun','C. Uzun','Can Uzun','MID','Frankfurt',14,'tur',false),
    _P('tur_kokcu','O. Kökçü','Orkun Kökçü','MID','Beşiktaş',8,'tur',false),
    _P('tur_yildiz','K. Yıldız','Kenan Yıldız','FWD','Juventus',20,'tur',false),
    _P('tur_akturkoglu','K. Aktürkoğlu','Kerem Aktürkoğlu','FWD','Fenerbahçe',7,'tur',false),
    _P('tur_akgun','Y. Akgün','Yunus Akgün','FWD','Galatasaray',9,'tur',false),
    /* ── URU (G2) ── */
    _P('uru_rochet','S. Rochet','Sergio Rochet','GK','Internacional',1,'uru',false),
    _P('uru_muslera','F. Muslera','Fernando Muslera','GK','Estudiantes',12,'uru',false),
    _P('uru_araujo','R. Araújo','Ronald Araújo','DEF','Barcelona',4,'uru',false),
    _P('uru_gimenez','J.M. Giménez','José María Giménez','DEF','Atlético Madrid',3,'uru',false),
    _P('uru_olivera','M. Olivera','Mathías Olivera','DEF','Nápoles',22,'uru',false),
    _P('uru_bentancur','R. Bentancur','Rodrigo Bentancur','MID','Tottenham',5,'uru',false),
    _P('uru_valverde','F. Valverde','Fede Valverde','MID','Real Madrid',8,'uru',false),
    _P('uru_ugarte','M. Ugarte','Manuel Ugarte','MID','Man. Utd',16,'uru',false),
    _P('uru_delacruz','N. De la Cruz','Nicolás De la Cruz','MID','Flamengo',10,'uru',false),
    _P('uru_nunez','D. Núñez','Darwin Núñez','FWD','Al Hilal',9,'uru',false),
    _P('uru_pellistri','F. Pellistri','Facundo Pellistri','MID','Panathinaikos',7,'uru',false),
    _P('uru_aguirre','R. Aguirre','Rodrigo Aguirre','FWD','Club América',19,'uru',false),
    /* ── SWE (G2) ── */
    _P('swe_johansson','V. Johansson','Viktor Johansson','GK','Stoke',1,'swe',false),
    _P('swe_lindelof','V. Lindelöf','Victor Lindelöf','DEF','Aston Villa',2,'swe',false),
    _P('swe_hien','I. Hien','Isak Hien','DEF','Atalanta',5,'swe',false),
    _P('swe_bergvall','L. Bergvall','Lucas Bergvall','MID','Tottenham',8,'swe',false),
    _P('swe_isak','A. Isak','Alexander Isak','FWD','Liverpool',11,'swe',false),
    _P('swe_gyokeres','V. Gyökeres','Viktor Gyökeres','FWD','Arsenal',9,'swe',false),
    _P('swe_elanga','A. Elanga','Anthony Elanga','FWD','Newcastle',7,'swe',false),
    _P('swe_kulusevski','D. Kulusevski','Dejan Kulusevski','MID','Tottenham',21,'swe',false),
    /* ── CRO (G2) ── */
    _P('cro_livakovic','D. Livaković','Dominik Livaković','GK','Dinamo Zagreb',1,'cro',false),
    _P('cro_gvardiol','J. Gvardiol','Joško Gvardiol','DEF','Man. City',6,'cro',false),
    _P('cro_sutalo','J. Šutalo','Josip Šutalo','DEF','Ajax',4,'cro',false),
    _P('cro_stanisic','J. Stanišić','Josip Stanišić','DEF','Bayern',2,'cro',false),
    _P('cro_modric','L. Modrić','Luka Modrić','MID','AC Milan',10,'cro',false),
    _P('cro_kovacic','M. Kovačić','Mateo Kovačić','MID','Man. City',8,'cro',false),
    _P('cro_sucic','L. Sučić','Luka Sučić','MID','Real Sociedad',16,'cro',false),
    _P('cro_baturina','M. Baturina','Martin Baturina','MID','Como',14,'cro',false),
    _P('cro_kramaric','A. Kramarić','Andrej Kramarić','FWD','Hoffenheim',9,'cro',false),
    _P('cro_budimir','A. Budimir','Ante Budimir','FWD','Osasuna',7,'cro',false),
    _P('cro_musa','P. Musa','Petar Musa','FWD','Dallas',11,'cro',false),
    /* ── SEN (G2) ── */
    _P('sen_mendy_e','E. Mendy','Édouard Mendy','GK','Al Ahli',1,'sen',false),
    _P('sen_koulibaly','K. Koulibaly','Kalidou Koulibaly','DEF','Al Hilal',3,'sen',false),
    _P('sen_niakhate','M. Niakhaté','Moussa Niakhaté','DEF','Lyon',5,'sen',false),
    _P('sen_hakimi_s','A. Seck','Abdoulaye Seck','DEF','Maccabi Haifa',4,'sen',false),
    _P('sen_ganegueye','I.G. Gueye','Idrissa Gana Gueye','MID','Everton',8,'sen',false),
    _P('sen_lcamara','L. Camara','Lamine Camara','MID','Monaco',7,'sen',false),
    _P('sen_pmsarr','P.M. Sarr','Pape Matar Sarr','MID','Tottenham',20,'sen',false),
    _P('sen_diarra','H. Diarra','Habib Diarra','MID','Sunderland',17,'sen',false),
    _P('sen_mane','S. Mané','Sadio Mané','FWD','Al Nassr',10,'sen',false),
    _P('sen_isarr','I. Sarr','Ismaïla Sarr','FWD','Crystal Palace',11,'sen',false),
    _P('sen_jackson','N. Jackson','Nicolas Jackson','FWD','Chelsea',9,'sen',false),
    _P('sen_indiaye','I. Ndiaye','Iliman Ndiaye','FWD','Everton',18,'sen',false),
    _P('sen_diao','A. Diao','Assane Diao','FWD','Como',19,'sen',false),
    /* ── JPN (G3) ── */
    _P('jpn_suzuki','Z. Suzuki','Zion Suzuki','GK','Parma',1,'jpn',false),
    _P('jpn_tomiyasu','T. Tomiyasu','Takehiro Tomiyasu','DEF','Ajax',5,'jpn',false),
    _P('jpn_itakura','K. Itakura','Ko Itakura','DEF','Ajax',3,'jpn',false),
    _P('jpn_sugawara','Y. Sugawara','Yukinari Sugawara','DEF','Southampton',2,'jpn',false),
    _P('jpn_hiroki_ito','H. Itô','Hiroki Itô','DEF','Bayern',4,'jpn',false),
    _P('jpn_endo','W. Endo','Wataru Endo','MID','Liverpool',6,'jpn',false),
    _P('jpn_kamada','D. Kamada','Daichi Kamada','MID','Crystal Palace',14,'jpn',false),
    _P('jpn_tanaka','A. Tanaka','Ao Tanaka','MID','Leeds',17,'jpn',false),
    _P('jpn_doan','R. Doan','Ritsu Doan','MID','Frankfurt',9,'jpn',false),
    _P('jpn_kubo','T. Kubo','Takefusa Kubo','MID','Real Sociedad',10,'jpn',false),
    _P('jpn_maeda','D. Maeda','Daizen Maeda','MID','Celtic',22,'jpn',false),
    _P('jpn_ueda','A. Ueda','Ayase Ueda','FWD','Feyenoord',11,'jpn',false),
    _P('jpn_mitoma','K. Mitoma','Kaoru Mitoma','FWD','Brighton',7,'jpn',false),
    /* ── CAN (G3) ── */
    _P('can_crepeau','M. Crépeaу','Maxime Crépeaу','GK','Orlando City',1,'can',false),
    _P('can_davies','A. Davies','Alphonso Davies','DEF','Bayern',3,'can',false),
    _P('can_johnston','A. Johnston','Alistair Johnston','DEF','Celtic',2,'can',false),
    _P('can_cornelius','D. Cornelius','Derek Cornelius','DEF','Rangers',5,'can',false),
    _P('can_eustaquio','S. Eustáquio','Stephen Eustáquio','MID','LAFC',7,'can',false),
    _P('can_osorio','J. Osorio','Jonathan Osorio','MID','Toronto',20,'can',false),
    _P('can_kone','I. Koné','Ismaël Koné','MID','Sassuolo',16,'can',false),
    _P('can_buchanan','T. Buchanan','Tajon Buchanan','MID','Villarreal',14,'can',false),
    _P('can_david','J. David','Jonathan David','FWD','Juventus',9,'can',false),
    _P('can_larin','C. Larin','Cyle Larin','FWD','Southampton',18,'can',false),
    _P('can_oluwaseyi','T. Oluwaseyi','Tani Oluwaseyi','FWD','Villarreal',19,'can',false),
    /* ── MEX (G3) ── */
    _P('mex_ochoa','G. Ochoa','Guillermo Ochoa','GK','AEL Limassol',1,'mex',false),
    _P('mex_rangel','R. Rangel','Raúl Rangel','GK','Chivas',23,'mex',false),
    _P('mex_edson','E. Álvarez','Edson Álvarez','DEF','Fenerbahçe',14,'mex',false),
    _P('mex_vasquez','J. Vásquez','Johan Vásquez','DEF','Genoa',5,'mex',false),
    _P('mex_obed','O. Vargas','Obed Vargas','MID','Atlético Madrid',8,'mex',false),
    _P('mex_fidalgo','Á. Fidalgo','Álvaro Fidalgo','MID','Real Betis',10,'mex',false),
    _P('mex_sgimenez','S. Giménez','Santiago Giménez','FWD','AC Milan',9,'mex',false),
    _P('mex_jimenez','R. Jiménez','Raúl Jiménez','FWD','Fulham',7,'mex',false),
    _P('mex_huerta','C. Huerta','César Huerta','FWD','Anderlecht',11,'mex',false),
    _P('mex_enciso','J. Enciso','Julio Enciso','FWD','Strasbourg',20,'mex',false),
    /* ── AUT (G3) ── */
    _P('aut_pentz','P. Pentz','Patrick Pentz','GK','Brøndby',1,'aut',false),
    _P('aut_alaba','D. Alaba','David Alaba','DEF','Real Madrid',6,'aut',false),
    _P('aut_danso','K. Danso','Kevin Danso','DEF','Tottenham',4,'aut',false),
    _P('aut_posch','S. Posch','Stefan Posch','DEF','Como',2,'aut',false),
    _P('aut_sabitzer','M. Sabitzer','Marcel Sabitzer','MID','BVB',8,'aut',false),
    _P('aut_xschlager','X. Schlager','Xaver Schlager','MID','Leipzig',14,'aut',false),
    _P('aut_laimer','K. Laimer','Konrad Laimer','MID','Bayern',7,'aut',false),
    _P('aut_arnautovic','M. Arnautović','Marko Arnautović','FWD','Red Star',9,'aut',false),
    _P('aut_gregoritsch','M. Gregoritsch','Michael Gregoritsch','FWD','Brøndby',10,'aut',false),
    _P('aut_kalajdzic','S. Kalajdzic','Sasa Kalajdzic','FWD','Wolves',11,'aut',false),
    /* ── USA (G3) ── */
    _P('usa_turner','M. Turner','Matt Turner','GK','New England',1,'usa',false),
    _P('usa_dest','S. Dest','Sergino Dest','DEF','PSV',2,'usa',false),
    _P('usa_robinson','A. Robinson','Antonee Robinson','DEF','Fulham',3,'usa',false),
    _P('usa_scally','J. Scally','Joe Scally','DEF','Gladbach',5,'usa',false),
    _P('usa_adams','T. Adams','Tyler Adams','MID','Bournemouth',4,'usa',false),
    _P('usa_mckennie','W. McKennie','Weston McKennie','MID','Juventus',8,'usa',false),
    _P('usa_reyna','G. Reyna','Giovanni Reyna','MID','Gladbach',7,'usa',false),
    _P('usa_tillman','M. Tillman','Malik Tillman','MID','Leverkusen',17,'usa',false),
    _P('usa_pulisic','C. Pulisic','Christian Pulisic','FWD','AC Milan',10,'usa',false),
    _P('usa_weah','T. Weah','Tim Weah','FWD','Marseille',11,'usa',false),
    _P('usa_balogun','F. Balogun','Folarin Balogun','FWD','Monaco',9,'usa',false),
    _P('usa_pepi','R. Pepi','Ricardo Pepi','FWD','PSV',22,'usa',false),
    _P('usa_aaronson','B. Aaronson','Brenden Aaronson','FWD','Leeds',14,'usa',false),
    /* ── BIH (G3) ── */
    _P('bih_vasilj','N. Vasilj','Nikola Vasilj','GK','St. Pauli',1,'bih',false),
    _P('bih_kolasinac','S. Kolašinac','Sead Kolašinac','DEF','Atalanta',5,'bih',false),
    _P('bih_dedic','A. Dedić','Amar Dedić','DEF','Benfica',2,'bih',false),
    _P('bih_tahirovic','B. Tahirović','Benjamin Tahirović','MID','Brøndby',8,'bih',false),
    _P('bih_demirovic','E. Demirović','Ermedin Demirović','FWD','Stuttgart',9,'bih',false),
    _P('bih_tabakovic','H. Tabakovic','Haris Tabakovic','FWD','Gladbach',11,'bih',false),
    _P('bih_dzeko','E. Džeko','Edin Džeko','FWD','Schalke',10,'bih',false),
    /* ── ECU (G3) ── */
    _P('ecu_galindez','H. Galindez','Hernán Galíndez','GK','Huracán',1,'ecu',false),
    _P('ecu_hincapie','P. Hincapié','Piero Hincapié','DEF','Arsenal',3,'ecu',false),
    _P('ecu_pacho','W. Pacho','Willian Pacho','DEF','PSG',4,'ecu',false),
    _P('ecu_estupinan','P. Estupiñán','Pervis Estupiñán','DEF','AC Milan',2,'ecu',false),
    _P('ecu_ordonez','J. Ordóñez','Joel Ordóñez','DEF','Club Brugge',5,'ecu',false),
    _P('ecu_caicedo','M. Caicedo','Moisés Caicedo','MID','Chelsea',10,'ecu',false),
    _P('ecu_kpaez','K. Páez','Kendry Páez','MID','River Plate',20,'ecu',false),
    _P('ecu_valencia','E. Valencia','Enner Valencia','FWD','Pachuca',13,'ecu',false),
    _P('ecu_krodriguez','K. Rodríguez','Kevin Rodríguez','FWD','Union SG',9,'ecu',false),
    _P('ecu_angulo','N. Angulo','Nilson Angulo','FWD','Sunderland',7,'ecu',false),
    /* ── CZE (G3) ── */
    _P('cze_kovar','M. Kovář','Matej Kovář','GK','PSV',1,'cze',false),
    _P('cze_stanek','J. Staněk','Jindřich Staněk','GK','Slavia',12,'cze',false),
    _P('cze_coufal','V. Coufal','Vladimír Coufal','DEF','Hoffenheim',2,'cze',false),
    _P('cze_hranac','R. Hranáč','Robin Hranáč','DEF','Hoffenheim',5,'cze',false),
    _P('cze_soucek','T. Souček','Tomáš Souček','MID','West Ham',28,'cze',false),
    _P('cze_sadilek','M. Sadílek','Michal Sadílek','MID','Slavia',6,'cze',false),
    _P('cze_sulc','P. Šulc','Pavel Šulc','MID','Lyon',14,'cze',false),
    _P('cze_schick','P. Schick','Patrik Schick','FWD','Leverkusen',9,'cze',false),
    _P('cze_hlozek','A. Hlôžek','Adam Hlôžek','FWD','Hoffenheim',11,'cze',false),
    _P('cze_kuchta','J. Kuchta','Jan Kuchta','FWD','Sparta',7,'cze',false),
    /* ── CIV (G4) ── */
    _P('civ_lafont','A. Lafont','Alban Lafont','GK','Panathinaikos',1,'civ',false),
    _P('civ_diomande','O. Diomandé','Ousmane Diomandé','DEF','Sporting',4,'civ',false),
    _P('civ_ndicka','E. Ndicka','Evan Ndicka','DEF','Roma',3,'civ',false),
    _P('civ_singo','W. Singo','Wilfried Singo','DEF','Galatasaray',2,'civ',false),
    _P('civ_sangare','I. Sangaré','Ibrahim Sangaré','MID','Nottingham F.',6,'civ',false),
    _P('civ_kessie','F. Kessié','Franck Kessié','MID','Al Ahli',5,'civ',false),
    _P('civ_adingra','S. Adingra','Simon Adingra','FWD','Monaco',11,'civ',false),
    _P('civ_diallo','A. Diallo','Amad Diallo','FWD','Man. Utd',19,'civ',false),
    _P('civ_wahi','E. Wahi','Elye Wahi','FWD','Nice',9,'civ',false),
    _P('civ_pepe','N. Pépé','Nicolas Pépé','FWD','Villarreal',7,'civ',false),
    _P('civ_bonny','A-Y. Bonny','Ange-Yoan Bonny','FWD','Inter',10,'civ',false),
    /* ── TUN (G4) ── */
    _P('tun_dahmen','A. Dahmen','Aymen Dahmen','GK','CS Sfaxien',1,'tun',false),
    _P('tun_bronn','D. Bronn','Dylan Bronn','DEF','Servette',3,'tun',false),
    _P('tun_talbi','M. Talbi','Montassar Talbi','DEF','Lorient',5,'tun',false),
    _P('tun_skhiri','E. Skhiri','Ellyes Skhiri','MID','Frankfurt',8,'tun',false),
    _P('tun_mejbri','H. Mejbri','Hannibal Mejbri','MID','Burnley',10,'tun',false),
    _P('tun_bslimane','A. Ben Slimane','Anis Ben Slimane','MID','Norwich',11,'tun',false),
    _P('tun_saad','E. Saad','Elias Saad','FWD','Hannover',7,'tun',false),
    /* ── EGY (G4) ── */
    _P('egy_elshenawy','M. El Shenawy','Mohamed El Shenawy','GK','Al Ahly',1,'egy',false),
    _P('egy_salah','M. Salah','Mohamed Salah','FWD','Liverpool',10,'egy',false),
    _P('egy_marmoush','O. Marmoush','Omar Marmoush','FWD','Man. City',9,'egy',false),
    _P('egy_trezeguet','Trezeguet','Mahmoud Trezeguet','MID','Al Ahly',11,'egy',false),
    _P('egy_adel','I. Adel','Ibrahim Adel','MID','Nordsjaelland',7,'egy',false),
    _P('egy_abdelkarim','H. Abdelkarim','Hamza Abdelkarim','FWD','Barcelona B',19,'egy',false),
    /* ── RSA (G4) ── */
    _P('rsa_williams','R. Williams','Ronwen Williams','GK','Mamelodi Sundowns',1,'rsa',false),
    _P('rsa_mokoena','T. Mokoena','Teboho Mokoena','MID','Mamelodi Sundowns',6,'rsa',false),
    _P('rsa_mofokeng','R. Mofokeng','Relebohile Mofokeng','FWD','Orlando Pirates',10,'rsa',false),
    _P('rsa_foster','L. Foster','Lyle Foster','FWD','Burnley',9,'rsa',false),
    _P('rsa_appollis','O. Appollis','Oswin Appollis','FWD','Orlando Pirates',11,'rsa',false),
    _P('rsa_makgopa','E. Makgopa','Evidence Makgopa','FWD','Orlando Pirates',7,'rsa',false),
    /* ── GHA (G4) ── */
    _P('gha_atizigi','L. Ati-Zigi','Lawrence Ati-Zigi','GK','St. Gallen',1,'gha',false),
    _P('gha_seidu','A. Seidu','Alidu Seidu','DEF','Rennes',2,'gha',false),
    _P('gha_partey','T. Partey','Thomas Partey','MID','Villarreal',5,'gha',false),
    _P('gha_issahaku','A.F. Issahaku','Abdul Fatawu Issahaku','MID','Leicester',10,'gha',false),
    _P('gha_kudus','M. Kudus','Mohammed Kudus','MID','West Ham',14,'gha',false),
    _P('gha_sulemana','K. Sulemana','Kamaldeen Sulemana','FWD','Atalanta',11,'gha',false),
    _P('gha_inkwilliams','I. Williams','Iñaki Williams','FWD','Athletic Club',9,'gha',false),
    _P('gha_jayew','J. Ayew','Jordan Ayew','FWD','Leicester',7,'gha',false),
    _P('gha_semenyo','A. Semenyo','Antoine Semenyo','FWD','Man. City',17,'gha',false),
    _P('gha_nuamah','E. Nuamah','Ernest Nuamah','FWD','Lyon',19,'gha',false),
    /* ── COD (G4) ── */
    _P('cod_mbemba','C. Mbemba','Chancel Mbemba','DEF','Lille',5,'cod',false),
    _P('cod_wanbissaka','A. Wan-Bissaka','Aaron Wan-Bissaka','DEF','West Ham',2,'cod',false),
    _P('cod_masuaku','A. Masuaku','Arthur Masuaku','DEF','Lens',3,'cod',false),
    _P('cod_mukau','N. Mukau','Ngal\'ayel Mukau','MID','Lille',8,'cod',false),
    _P('cod_wissa','Y. Wissa','Yoane Wissa','FWD','Newcastle',9,'cod',false),
    _P('cod_banza','S. Banza','Simon Banza','FWD','Al Jazira',11,'cod',false),
    _P('cod_bakambu','C. Bakambu','Cédric Bakambu','FWD','Real Betis',7,'cod',false),
    /* ── ALG (G4) ── */
    _P('alg_bensebaini','R. Bensebaini','Ramy Bensebaini','DEF','BVB',3,'alg',false),
    _P('alg_aitnouri','R. Aït-Nouri','Rayan Aït-Nouri','DEF','Man. City',2,'alg',false),
    _P('alg_bentaleb','N. Bentaleb','Nabil Bentaleb','MID','Lille',8,'alg',false),
    _P('alg_maza','I. Maza','Ibrahim Maza','MID','Leverkusen',10,'alg',false),
    _P('alg_chaibi','F. Chaibi','Fares Chaibi','MID','Frankfurt',14,'alg',false),
    _P('alg_mahrez','R. Mahrez','Riyad Mahrez','FWD','Al Ahli',26,'alg',false),
    _P('alg_amoura','M. Amoura','Mohamed Amoura','FWD','Wolfsburg',9,'alg',false),
    _P('alg_gouiri','A. Gouiri','Amine Gouiri','FWD','Marseille',7,'alg',false),
    /* ── SCO (G5) ── */
    _P('sco_gordon','C. Gordon','Craig Gordon','GK','Hearts',1,'sco',false),
    _P('sco_gunn','A. Gunn','Angus Gunn','GK','Nottingham F.',12,'sco',false),
    _P('sco_robertson','A. Robertson','Andy Robertson','DEF','Liverpool',3,'sco',false),
    _P('sco_tierney','K. Tierney','Kieran Tierney','DEF','Celtic',5,'sco',false),
    _P('sco_mckenna','S. McKenna','Scott McKenna','DEF','Dinamo Zagreb',4,'sco',false),
    _P('sco_hickey','A. Hickey','Aaron Hickey','DEF','Brentford',2,'sco',false),
    _P('sco_mcginn','J. McGinn','John McGinn','MID','Aston Villa',7,'sco',false),
    _P('sco_mctominay','S. McTominay','Scott McTominay','MID','Nápoles',8,'sco',false),
    _P('sco_lferguson','L. Ferguson','Lewis Ferguson','MID','Bologna',6,'sco',false),
    _P('sco_adams','C. Adams','Che Adams','FWD','Torino',11,'sco',false),
    _P('sco_dykes','L. Dykes','Lyndon Dykes','FWD','Charlton',9,'sco',false),
    _P('sco_shankland','L. Shankland','Lawrence Shankland','FWD','Rangers',10,'sco',false),
    /* ── AUS (G5) ── */
    _P('aus_ryan','M. Ryan','Maty Ryan','GK','Levante',1,'aus',false),
    _P('aus_souttar','H. Souttar','Harry Souttar','DEF','Leicester',3,'aus',false),
    _P('aus_circati','A. Circati','Alessandro Circati','DEF','Parma',5,'aus',false),
    _P('aus_irvine','J. Irvine','Jackson Irvine','MID','St. Pauli',8,'aus',false),
    _P('aus_hrustic','A. Hrustic','Ajdin Hrustic','MID','Heracles',10,'aus',false),
    _P('aus_irankunda','N. Irankunda','Nestory Irankunda','FWD','Watford',11,'aus',false),
    _P('aus_leckie','M. Leckie','Mathew Leckie','FWD','Melbourne City',7,'aus',false),
    _P('aus_yengi','T. Yengi','Tete Yengi','FWD','Machida Zelvia',9,'aus',false),
    _P('aus_volpato','C. Volpato','Cristian Volpato','FWD','Sassuolo',14,'aus',false),
    /* ── PAR (G5) ── */
    _P('par_olveira','G. Olveira','Gastón Olveira','GK','Olimpia',1,'par',false),
    _P('par_gomez_g','G. Gómez','Gustavo Gómez','DEF','Palmeiras',4,'par',false),
    _P('par_balbuena','F. Balbuena','Fabián Balbuena','DEF','Grêmio',3,'par',false),
    _P('par_cubas','A. Cubas','Andrés Cubas','MID','Vancouver',8,'par',false),
    _P('par_dgomez','D. Gómez','Diego Gómez','MID','Brighton',10,'par',false),
    _P('par_enciso_p','J. Enciso','Julio Enciso','FWD','Strasbourg',11,'par',false),
    _P('par_almiron','M. Almirón','Miguel Almirón','FWD','Atlanta Utd',7,'par',false),
    _P('par_sanabria','A. Sanabria','Antonio Sanabria','FWD','Cremonese',9,'par',false),
    _P('par_sosa','R. Sosa','Ramón Sosa','FWD','Palmeiras',22,'par',false),
    /* ── KSA (G5) ── */
    _P('ksa_alowais','M. Al Owais','Mohammed Al Owais',  'GK','Al Ula',1,'ksa',false),
    _P('ksa_tambakti','H. Tambakti','Hassan Tambakti','DEF','Al Hilal',5,'ksa',false),
    _P('ksa_abdulhamid','S. Abdulhamid','Saud Abdulhamid','DEF','Lens',2,'ksa',false),
    _P('ksa_kanno','M. Kanno','Mohammed Kanno','MID','Al Hilal',8,'ksa',false),
    _P('ksa_ndawsari','N. Al Dawsari','Nasser Al Dawsari','MID','Al Hilal',16,'ksa',false),
    _P('ksa_sdawsari','S. Al Dawsari','Salem Al Dawsari','MID','Al Hilal',10,'ksa',false),
    _P('ksa_alburaikan','F. Al Buraikan','Firas Al Buraikan','FWD','Al Ahli',9,'ksa',false),
    _P('ksa_alshehri','S. Al Shehri','Saleh Al Shehri','FWD','Al Ittihad',11,'ksa',false),
    _P('ksa_alhamdan','A. Al Hamdan','Abdullah Al Hamdan','FWD','Al Nassr',7,'ksa',false),
    /* ── KOR (G5) ── */
    _P('kor_kim_sg','S.G. Kim','Kim Seung-gyu','GK','FC Tokyo',1,'kor',false),
    _P('kor_kim_mj','M.J. Kim','Kim Min-jae','DEF','Bayern',3,'kor',false),
    _P('kor_son','H.M. Son','Son Heung-min','FWD','LAFC',7,'kor',false),
    _P('kor_lee_ki','K.I. Lee','Lee Kang-in','MID','PSG',10,'kor',false),
    _P('kor_hwang_hc','H.C. Hwang','Hwang Hee-chan','FWD','Wolves',9,'kor',false),
    _P('kor_hwang_ib','I.B. Hwang','Hwang In-beom','MID','Feyenoord',6,'kor',false),
    _P('kor_bae','J.H. Bae','Bae Jun-ho','MID','Stoke',8,'kor',false),
    _P('kor_cho','G.S. Cho','Cho Gue-sung','FWD','Midtjylland',11,'kor',false),
    _P('kor_yang','H.J. Yang','Hyun-Jun Yang','MID','Celtic',14,'kor',false),
    /* ── QAT (G5) ── */
    _P('qat_barsham','M. Barsham','Meshaal Barsham','GK','Al Sadd',1,'qat',false),
    _P('qat_afif','A. Afif','Akram Afif','FWD','Al Sadd',11,'qat',false),
    _P('qat_almoez','A. Ali','Almoez Ali','FWD','Al Duhail',19,'qat',false),
    _P('qat_boudiaf','K. Boudiaf','Karim Boudiaf','MID','Al Duhail',5,'qat',false),
    _P('qat_alhaydos','H. Al Haydos','Hassan Al Haydos','FWD','Al Sadd',10,'qat',false),
    _P('qat_edmilson','Edmilson Jr.','Edmilson Junior','FWD','Al Duhail',9,'qat',false),
    /* ── IRQ (G6) ── */
    _P('irq_iqbal','Z. Iqbal','Zidane Iqbal','MID','Utrecht',8,'irq',false),
    _P('irq_alhamadi','A. Al-Hamadi','Ali Al-Hamadi','FWD','Ipswich',9,'irq',false),
    _P('irq_jassim','A. Jassim','Ali Jassim','FWD','Al Najma',10,'irq',false),
    _P('irq_aymen','A. Hussein','Aymen Hussein','FWD','Al Karma',11,'irq',false),
    _P('irq_mohanad','M. Ali','Mohanad Ali','FWD','Dibba',7,'irq',false),
    /* ── JOR (G6) ── */
    _P('jor_taamari','M. Al-Taamari','Musa Al-Taamari','FWD','Rennes',10,'jor',false),
    _P('jor_azaizeh','A. Azaizeh','Ali Azaizeh','FWD','Al Shabab',7,'jor',false),
    _P('jor_rawabdeh','N. Al-Rawabdeh','Noor Al-Rawabdeh','MID','Selangor',8,'jor',false),
    /* ── NZL (G6) ── */
    _P('nzl_wood','C. Wood','Chris Wood','FWD','Nottingham F.',9,'nzl',false),
    _P('nzl_stamenic','M. Stamenic','Marko Stamenic','MID','Swansea',8,'nzl',false),
    _P('nzl_cacace','L. Cacace','Liberato Cacace','DEF','Wrexham',3,'nzl',false),
    _P('nzl_bindon','T. Bindon','Tyler Bindon','DEF','Nottingham F.',4,'nzl',false),
    /* ── CUR (G6) ── */
    _P('cur_chong','T. Chong','Tahith Chong','FWD','Sheffield Utd',10,'cur',false),
    _P('cur_obispo','A. Obispo','Armando Obispo','DEF','PSV',5,'cur',false),
    _P('cur_bacuna','L. Bacuna','Leandro Bacuna','MID','Igdır',8,'cur',false),
    _P('cur_locadia','J. Locadia','Jurgen Locadia','FWD','Miami FC',9,'cur',false),
    _P('cur_bazoer','R. Bazoer','Riechedly Bazoer','DEF','Konyaspor',4,'cur',false),
    /* ── PAN (G6) ── */
    _P('pan_carrasquilla','A. Carrasquilla','Adalberto Carrasquilla','MID','UNAM',8,'pan',false),
    _P('pan_fajardo','J. Fajardo','José Fajardo','FWD','U. Católica',9,'pan',false),
    _P('pan_diaz','I. Díaz','Ismael Díaz','FWD','León',10,'pan',false),
    _P('pan_murillo','M. Murillo','Michael Murillo','DEF','Beşiktaş',2,'pan',false),
    _P('pan_barcenas','Y. Bárcenas','Yoel Bárcenas','MID','Mazatlán',7,'pan',false),
    /* ── CPV (G6) ── */
    _P('cpv_logancosta','L. Costa','Logan Costa','DEF','Villarreal',5,'cpv',false),
    _P('cpv_ryan_mendes','R. Mendes','Ryan Mendes','FWD','Igdır',7,'cpv',false),
    _P('cpv_garry','G. Rodrigues','Garry Rodrigues','MID','Apollon',10,'cpv',false),
    _P('cpv_jovane','J. Cabral','Jovane Cabral','FWD','Estrela Amadora',11,'cpv',false),
    _P('cpv_laros','L. Duarte','Laros Duarte','MID','Puskás Akadémia',8,'cpv',false),
    /* ── IRN (G6) ── */
    _P('irn_beiranvand','A. Beiranvand','Alireza Beiranvand','GK','Tractor',1,'irn',false),
    _P('irn_taremi','M. Taremi','Mehdi Taremi','FWD','Olympiakos',9,'irn',false),
    _P('irn_jahanbakhsh','A. Jahanbakhsh','Alireza Jahanbakhsh','MID','Dender',7,'irn',false),
    _P('irn_ezatolahi','S. Ezatolahi','Saeid Ezatolahi','MID','Shabab Al Ahli',8,'irn',false),
    _P('irn_ghaedi','M. Ghaedi','Mehdi Ghaedi','MID','Al Nasr',10,'irn',false),
    _P('irn_hajsafi','E. Hajsafi','Ehsan Hajsafi','DEF','Sepahan',3,'irn',false),
    _P('irn_alipour','A. Alipour','Ali Alipour','FWD','Persepolis',11,'irn',false),
    /* ── UZB (G6) ── */
    _P('uzb_shomurodov','E. Shomurodov','Eldor Shomurodov','FWD','Beşiktaş',9,'uzb',false),
    _P('uzb_fayzullaev','A. Fayzullaev','Abbosbek Fayzullaev','MID','İstanbul Başakşehir',10,'uzb',false),
    _P('uzb_khusanov','A. Khusanov','Abdukodir Khusanov','DEF','Man. City',5,'uzb',false),
    _P('uzb_urunov','O. Urunov','Oston Urunov','MID','Persepolis',8,'uzb',false),
    _P('uzb_masharipov','J. Masharipov','Jaloliddin Masharipov','MID','Esteghlal',7,'uzb',false),
    _P('uzb_sergeev','I. Sergeev','Igor Sergeev','FWD','Persepolis',11,'uzb',false),
    /* ── HAI (G6) ── */
    _P('hai_bellegarde','J-R. Bellegarde','Jean-Ricner Bellegarde','MID','Wolves',8,'hai',false),
    _P('hai_isidor','W. Isidor','Wilson Isidor','FWD','Sunderland',9,'hai',false),
    _P('hai_nazon','D. Nazon','Duckens Nazon','FWD','Esteghlal',10,'hai',false),
    _P('hai_pierrot','F. Pierrot','Frantzdy Pierrot','FWD','Çaykur Rizespor',7,'hai',false),
    _P('hai_casimir','J. Casimir','Josué Casimir','FWD','Auxerre',11,'hai',false),
  ];

  const myPicks = {
    g1:[], g2:[], g3:[], g4:[], g5:null, g6:[],
    goalscorer:{}, duo:[null, null],
  };

  const leaderboard = [
    { rank:1,  name:'Laura Vidal',  user:'@lau',      pts:148, av:'LV', col:'#D8131A', trend:'+2', exact:9  },
    { rank:2,  name:'Diego Romero', user:'@dirom',    pts:142, av:'DR', col:'#27E5D4', trend:'-1', exact:8  },
    { rank:3,  name:'Marta Ibáñez', user:'@martai',   pts:139, av:'MI', col:'#8C6BFF', trend:'+1', exact:7  },
    { rank:4,  name:'Tú',           user:'@tucuenta', pts:131, av:'TÚ', col:'#FDD301', me:true, trend:'+3', exact:7 },
    { rank:5,  name:'Carlos Vega',  user:'@cvega',    pts:128, av:'CV', col:'#F79516', trend:'-2', exact:6  },
    { rank:6,  name:'Nuria Sanz',   user:'@nuri',     pts:124, av:'NS', col:'#ABCB2D', trend:'0',  exact:6  },
    { rank:7,  name:'Pablo Gil',    user:'@pgil',     pts:119, av:'PG', col:'#4DA6FF', trend:'+1', exact:5  },
    { rank:8,  name:'Eva Torres',   user:'@evat',     pts:115, av:'ET', col:'#FF5FA2', trend:'-1', exact:5  },
    { rank:9,  name:'Hugo Mora',    user:'@hugom',    pts:111, av:'HM', col:'#3DE08A', trend:'+2', exact:4  },
    { rank:10, name:'Sara León',    user:'@saral',    pts:108, av:'SL', col:'#ABCB2D', trend:'-3', exact:4  },
  ];

  const leagues = [
    { id:'l1', name:'Los Cracks del Finde', members:14, pot:'140 €', me:'4º', color:'#D8131A', code:'CRACK26' },
    { id:'l2', name:'Oficina FC',           members:9,  pot:'90 €',  me:'2º', color:'#27E5D4', code:'OFICFC'  },
    { id:'l3', name:'Familia Vidal',        members:6,  pot:'60 €',  me:'1º', color:'#8C6BFF', code:'VIDAL26' },
  ];

  const badges = [
    { id:'b1', name:'Pleno al 15',   got:true,  col:'#FDD301', ic:'target' },
    { id:'b2', name:'Racha x5',      got:true,  col:'#D8131A', ic:'fire'   },
    { id:'b3', name:'Madrugador',    got:true,  col:'#27E5D4', ic:'clock'  },
    { id:'b4', name:'Top 3 jornada', got:true,  col:'#F79516', ic:'medal'  },
    { id:'b5', name:'Profeta',       got:false, col:'#8C6BFF', ic:'crown'  },
    { id:'b6', name:'Sin fallos',    got:false, col:'#4DA6FF', ic:'shield' },
  ];

  const bracket = {
    r16:[
      {h:'arg',a:'usa',win:'arg'}, {h:'fra',a:'mex',win:'fra'},
      {h:'esp',a:'cro',win:'esp'}, {h:'bra',a:'nld',win:'bra'},
      {h:'eng',a:'sen',win:'eng'}, {h:'por',a:'bel',win:'por'},
      {h:'ale',a:'uru',win:'ale'}, {h:'col',a:'mar',win:'mar'},
    ],
    qf:[
      {h:'arg',a:'fra',win:'arg'}, {h:'esp',a:'bra',win:'bra'},
      {h:'eng',a:'por',win:'eng'}, {h:'ale',a:'mar',win:'ale'},
    ],
    sf:[
      {h:'arg',a:'bra',win:'arg'}, {h:'eng',a:'ale',win:'eng'},
    ],
    final:[{h:'arg',a:'eng',win:'arg'}],
    champion:'arg',
  };

  const activity = [
    { who:'Diego Romero',  act:'completó su selección',     detail:'11 selecciones listas', when:'hace 1 h', col:'#27E5D4', av:'DR' },
    { who:'Laura Vidal',   act:'actualizó su Dúo Dinámico', detail:'Mbappé + Bellingham',    when:'hace 3 h', col:'#D8131A', av:'LV' },
    { who:'Marta Ibáñez',  act:'se unió a la porra',        detail:'Los Cracks del Finde',   when:'hace 5 h', col:'#8C6BFF', av:'MI' },
  ];

  const matches = [
    { id:'m1',g:'D',home:'arg',away:'cro',date:'JUN 13',time:'21:00',venue:'MetLife · NJ',   status:'soon' },
    { id:'m2',g:'A',home:'mex',away:'nld',date:'JUN 13',time:'18:00',venue:'Azteca · CDMX',  status:'live', live:'1 - 0', min:"63'" },
    { id:'m3',g:'C',home:'usa',away:'ale',date:'JUN 14',time:'20:00',venue:'SoFi · LA',      status:'soon' },
    { id:'m4',g:'E',home:'esp',away:'uru',date:'JUN 14',time:'17:00',venue:'BC Place · VAN', status:'soon' },
    { id:'m5',g:'G',home:'bra',away:'por',date:'JUN 15',time:'21:00',venue:'AT&T · DAL',     status:'soon' },
  ];

  const deadline = new Date('2026-06-11T17:00:00');

  const teamPts = {
    esp:{group:0,knockout:0,total:0}, eng:{group:0,knockout:0,total:0},
    bra:{group:0,knockout:0,total:0}, por:{group:0,knockout:0,total:0},
    arg:{group:0,knockout:0,total:0}, fra:{group:0,knockout:0,total:0},
    ale:{group:0,knockout:0,total:0}, nld:{group:0,knockout:0,total:0},
    col:{group:0,knockout:0,total:0}, mar:{group:0,knockout:0,total:0},
    bel:{group:0,knockout:0,total:0}, sui:{group:0,knockout:0,total:0},
    nor:{group:0,knockout:0,total:0}, tur:{group:0,knockout:0,total:0},
    uru:{group:0,knockout:0,total:0}, swe:{group:0,knockout:0,total:0},
    cro:{group:0,knockout:0,total:0}, sen:{group:0,knockout:0,total:0},
    jpn:{group:0,knockout:0,total:0}, can:{group:0,knockout:0,total:0},
    mex:{group:0,knockout:0,total:0}, aut:{group:0,knockout:0,total:0},
    usa:{group:0,knockout:0,total:0}, bih:{group:0,knockout:0,total:0},
    ecu:{group:0,knockout:0,total:0}, cze:{group:0,knockout:0,total:0},
    civ:{group:0,knockout:0,total:0}, tun:{group:0,knockout:0,total:0},
    egy:{group:0,knockout:0,total:0}, rsa:{group:0,knockout:0,total:0},
    gha:{group:0,knockout:0,total:0}, cod:{group:0,knockout:0,total:0},
    alg:{group:0,knockout:0,total:0}, sco:{group:0,knockout:0,total:0},
    aus:{group:0,knockout:0,total:0}, par:{group:0,knockout:0,total:0},
    ksa:{group:0,knockout:0,total:0}, kor:{group:0,knockout:0,total:0},
    qat:{group:0,knockout:0,total:0}, irq:{group:0,knockout:0,total:0},
    jor:{group:0,knockout:0,total:0}, nzl:{group:0,knockout:0,total:0},
    cur:{group:0,knockout:0,total:0}, pan:{group:0,knockout:0,total:0},
    cpv:{group:0,knockout:0,total:0}, irn:{group:0,knockout:0,total:0},
    uzb:{group:0,knockout:0,total:0}, hai:{group:0,knockout:0,total:0},
  };

  window.DB = {
    T, TEAM_DB,
    porraGroups, scoring, players, myPicks,
    leaderboard, leagues, badges, bracket, activity, matches, deadline,
    teamPts,
    FLAG, getTeamsByCoef, autoAssignDraft,
  };
})();
